project_id = "wtnebvhrjnpygkftjreo"

[functions.contact-submit]
verify_jwt = false

[functions.ad-track]
verify_jwt = false

[functions.ad-redirect]
verify_jwt = false

[functions.create-ad-checkout]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.create-donation-checkout]
verify_jwt = false

[functions.donation-webhook]
verify_jwt = false

[functions.grant-admin-once]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false

[functions.log-referral-click]
verify_jwt = false

[functions.process-payment-referrals]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
