project_id = "wtnebvhrjnpygkftjreo"

[functions.contact-submit]
verify_jwt = false

[functions.ad-track]
verify_jwt = false

[functions.ad-redirect]
verify_jwt = false

[functions.create-ad-checkout]
verify_jwt = true
