-- Add Library page translations
INSERT INTO app_translations (language, key, value) VALUES
-- English
('en', 'library.title', 'My Library'),
('en', 'library.description', 'Track your custom song requests and access your completed songs.'),
('en', 'library.loading', 'Loading your library...'),
('en', 'library.back_to_home', 'Back to Home'),
('en', 'library.my_songs', 'My Songs'),
('en', 'library.custom_songs', '🎁 Custom Songs'),
('en', 'library.my_requests', 'My Requests'),
('en', 'library.no_songs_title', 'No Songs Yet'),
('en', 'library.no_songs_description', 'You haven''t purchased any songs yet. Start by exploring our library or requesting a custom song.'),
('en', 'library.browse_songs', 'Browse Songs'),
('en', 'library.request_custom_song', 'Request Custom Song'),
('en', 'library.purchased_on', 'Purchased on'),
('en', 'library.view', 'View'),
('en', 'library.download', 'Download'),
('en', 'library.no_custom_songs_title', 'No custom songs yet.'),
('en', 'library.no_custom_songs_description', 'Request your own song and see it here when ready.'),
('en', 'library.your_custom_song', 'Your Custom Song'),
('en', 'library.download_lyrics', '📄 Download Lyrics'),
('en', 'library.download_audio', '🎵 Download Audio'),
('en', 'library.created_on', 'Created on'),
('en', 'library.no_requests_title', 'No Custom Requests Yet'),
('en', 'library.no_requests_description', 'Start by requesting your first custom song. Our team will work on it and you''ll see updates here.'),
('en', 'library.request_first_song', 'Request First Song'),
('en', 'library.requested_on', 'Requested on'),

-- French
('fr', 'library.title', 'Ma Bibliothèque'),
('fr', 'library.description', 'Suivez vos demandes de chansons personnalisées et accédez à vos chansons terminées.'),
('fr', 'library.loading', 'Chargement de votre bibliothèque...'),
('fr', 'library.back_to_home', 'Retour à l''accueil'),
('fr', 'library.my_songs', 'Mes Chansons'),
('fr', 'library.custom_songs', '🎁 Chansons Personnalisées'),
('fr', 'library.my_requests', 'Mes Demandes'),
('fr', 'library.no_songs_title', 'Aucune Chanson Encore'),
('fr', 'library.no_songs_description', 'Vous n''avez encore acheté aucune chanson. Commencez par explorer notre bibliothèque ou demander une chanson personnalisée.'),
('fr', 'library.browse_songs', 'Parcourir les Chansons'),
('fr', 'library.request_custom_song', 'Demander une Chanson Personnalisée'),
('fr', 'library.purchased_on', 'Acheté le'),
('fr', 'library.view', 'Voir'),
('fr', 'library.download', 'Télécharger'),
('fr', 'library.no_custom_songs_title', 'Aucune chanson personnalisée encore.'),
('fr', 'library.no_custom_songs_description', 'Demandez votre propre chanson et voyez-la ici quand elle sera prête.'),
('fr', 'library.your_custom_song', 'Votre Chanson Personnalisée'),
('fr', 'library.download_lyrics', '📄 Télécharger les Paroles'),
('fr', 'library.download_audio', '🎵 Télécharger l''Audio'),
('fr', 'library.created_on', 'Créé le'),
('fr', 'library.no_requests_title', 'Aucune Demande Personnalisée Encore'),
('fr', 'library.no_requests_description', 'Commencez par demander votre première chanson personnalisée. Notre équipe y travaillera et vous verrez les mises à jour ici.'),
('fr', 'library.request_first_song', 'Demander Première Chanson'),
('fr', 'library.requested_on', 'Demandé le'),

-- Spanish
('es', 'library.title', 'Mi Biblioteca'),
('es', 'library.description', 'Rastrea tus solicitudes de canciones personalizadas y accede a tus canciones completadas.'),
('es', 'library.loading', 'Cargando tu biblioteca...'),
('es', 'library.back_to_home', 'Volver al Inicio'),
('es', 'library.my_songs', 'Mis Canciones'),
('es', 'library.custom_songs', '🎁 Canciones Personalizadas'),
('es', 'library.my_requests', 'Mis Solicitudes'),
('es', 'library.no_songs_title', 'Aún No Hay Canciones'),
('es', 'library.no_songs_description', 'Aún no has comprado ninguna canción. Comienza explorando nuestra biblioteca o solicitando una canción personalizada.'),
('es', 'library.browse_songs', 'Explorar Canciones'),
('es', 'library.request_custom_song', 'Solicitar Canción Personalizada'),
('es', 'library.purchased_on', 'Comprado el'),
('es', 'library.view', 'Ver'),
('es', 'library.download', 'Descargar'),
('es', 'library.no_custom_songs_title', 'Aún no hay canciones personalizadas.'),
('es', 'library.no_custom_songs_description', 'Solicita tu propia canción y verla aquí cuando esté lista.'),
('es', 'library.your_custom_song', 'Tu Canción Personalizada'),
('es', 'library.download_lyrics', '📄 Descargar Letras'),
('es', 'library.download_audio', '🎵 Descargar Audio'),
('es', 'library.created_on', 'Creado el'),
('es', 'library.no_requests_title', 'Aún No Hay Solicitudes Personalizadas'),
('es', 'library.no_requests_description', 'Comienza solicitando tu primera canción personalizada. Nuestro equipo trabajará en ella y verás las actualizaciones aquí.'),
('es', 'library.request_first_song', 'Solicitar Primera Canción'),
('es', 'library.requested_on', 'Solicitado el'),

-- German
('de', 'library.title', 'Meine Bibliothek'),
('de', 'library.description', 'Verfolgen Sie Ihre benutzerdefinierten Song-Anfragen und greifen Sie auf Ihre fertigen Songs zu.'),
('de', 'library.loading', 'Lade deine Bibliothek...'),
('de', 'library.back_to_home', 'Zurück zur Startseite'),
('de', 'library.my_songs', 'Meine Songs'),
('de', 'library.custom_songs', '🎁 Benutzerdefinierte Songs'),
('de', 'library.my_requests', 'Meine Anfragen'),
('de', 'library.no_songs_title', 'Noch Keine Songs'),
('de', 'library.no_songs_description', 'Sie haben noch keine Songs gekauft. Beginnen Sie mit der Erkundung unserer Bibliothek oder fordern Sie einen benutzerdefinierten Song an.'),
('de', 'library.browse_songs', 'Songs Durchsuchen'),
('de', 'library.request_custom_song', 'Benutzerdefinierten Song Anfordern'),
('de', 'library.purchased_on', 'Gekauft am'),
('de', 'library.view', 'Ansehen'),
('de', 'library.download', 'Herunterladen'),
('de', 'library.no_custom_songs_title', 'Noch keine benutzerdefinierten Songs.'),
('de', 'library.no_custom_songs_description', 'Fordern Sie Ihren eigenen Song an und sehen Sie ihn hier, wenn er fertig ist.'),
('de', 'library.your_custom_song', 'Ihr Benutzerdefinierter Song'),
('de', 'library.download_lyrics', '📄 Texte Herunterladen'),
('de', 'library.download_audio', '🎵 Audio Herunterladen'),
('de', 'library.created_on', 'Erstellt am'),
('de', 'library.no_requests_title', 'Noch Keine Benutzerdefinierten Anfragen'),
('de', 'library.no_requests_description', 'Beginnen Sie mit der Anforderung Ihres ersten benutzerdefinierten Songs. Unser Team wird daran arbeiten und Sie sehen Updates hier.'),
('de', 'library.request_first_song', 'Ersten Song Anfordern'),
('de', 'library.requested_on', 'Angefordert am'),

-- Portuguese
('pt', 'library.title', 'Minha Biblioteca'),
('pt', 'library.description', 'Acompanhe suas solicitações de músicas personalizadas e acesse suas músicas concluídas.'),
('pt', 'library.loading', 'Carregando sua biblioteca...'),
('pt', 'library.back_to_home', 'Voltar ao Início'),
('pt', 'library.my_songs', 'Minhas Músicas'),
('pt', 'library.custom_songs', '🎁 Músicas Personalizadas'),
('pt', 'library.my_requests', 'Minhas Solicitações'),
('pt', 'library.no_songs_title', 'Ainda Não Há Músicas'),
('pt', 'library.no_songs_description', 'Você ainda não comprou nenhuma música. Comece explorando nossa biblioteca ou solicitando uma música personalizada.'),
('pt', 'library.browse_songs', 'Explorar Músicas'),
('pt', 'library.request_custom_song', 'Solicitar Música Personalizada'),
('pt', 'library.purchased_on', 'Comprado em'),
('pt', 'library.view', 'Ver'),
('pt', 'library.download', 'Baixar'),
('pt', 'library.no_custom_songs_title', 'Ainda não há músicas personalizadas.'),
('pt', 'library.no_custom_songs_description', 'Solicite sua própria música e veja aqui quando estiver pronta.'),
('pt', 'library.your_custom_song', 'Sua Música Personalizada'),
('pt', 'library.download_lyrics', '📄 Baixar Letras'),
('pt', 'library.download_audio', '🎵 Baixar Áudio'),
('pt', 'library.created_on', 'Criado em'),
('pt', 'library.no_requests_title', 'Ainda Não Há Solicitações Personalizadas'),
('pt', 'library.no_requests_description', 'Comece solicitando sua primeira música personalizada. Nossa equipe trabalhará nela e você verá atualizações aqui.'),
('pt', 'library.request_first_song', 'Solicitar Primeira Música'),
('pt', 'library.requested_on', 'Solicitado em'),

-- Italian
('it', 'library.title', 'La Mia Biblioteca'),
('it', 'library.description', 'Traccia le tue richieste di canzoni personalizzate e accedi alle tue canzoni completate.'),
('it', 'library.loading', 'Caricamento della tua biblioteca...'),
('it', 'library.back_to_home', 'Torna alla Home'),
('it', 'library.my_songs', 'Le Mie Canzoni'),
('it', 'library.custom_songs', '🎁 Canzoni Personalizzate'),
('it', 'library.my_requests', 'Le Mie Richieste'),
('it', 'library.no_songs_title', 'Ancora Nessuna Canzone'),
('it', 'library.no_songs_description', 'Non hai ancora acquistato nessuna canzone. Inizia esplorando la nostra biblioteca o richiedendo una canzone personalizzata.'),
('it', 'library.browse_songs', 'Sfoglia Canzoni'),
('it', 'library.request_custom_song', 'Richiedi Canzone Personalizzata'),
('it', 'library.purchased_on', 'Acquistato il'),
('it', 'library.view', 'Visualizza'),
('it', 'library.download', 'Scarica'),
('it', 'library.no_custom_songs_title', 'Ancora nessuna canzone personalizzata.'),
('it', 'library.no_custom_songs_description', 'Richiedi la tua canzone e vedila qui quando sarà pronta.'),
('it', 'library.your_custom_song', 'La Tua Canzone Personalizzata'),
('it', 'library.download_lyrics', '📄 Scarica Testi'),
('it', 'library.download_audio', '🎵 Scarica Audio'),
('it', 'library.created_on', 'Creato il'),
('it', 'library.no_requests_title', 'Ancora Nessuna Richiesta Personalizzata'),
('it', 'library.no_requests_description', 'Inizia richiedendo la tua prima canzone personalizzata. Il nostro team ci lavorerà e vedrai gli aggiornamenti qui.'),
('it', 'library.request_first_song', 'Richiedi Prima Canzone'),
('it', 'library.requested_on', 'Richiesto il'),

-- Arabic
('ar', 'library.title', 'مكتبتي'),
('ar', 'library.description', 'تتبع طلبات الأغاني المخصصة الخاصة بك والوصول إلى أغانيك المكتملة.'),
('ar', 'library.loading', 'جاري تحميل مكتبتك...'),
('ar', 'library.back_to_home', 'العودة للرئيسية'),
('ar', 'library.my_songs', 'أغانيي'),
('ar', 'library.custom_songs', '🎁 الأغاني المخصصة'),
('ar', 'library.my_requests', 'طلباتي'),
('ar', 'library.no_songs_title', 'لا توجد أغاني بعد'),
('ar', 'library.no_songs_description', 'لم تشتر أي أغاني بعد. ابدأ باستكشاف مكتبتنا أو اطلب أغنية مخصصة.'),
('ar', 'library.browse_songs', 'تصفح الأغاني'),
('ar', 'library.request_custom_song', 'طلب أغنية مخصصة'),
('ar', 'library.purchased_on', 'تم الشراء في'),
('ar', 'library.view', 'عرض'),
('ar', 'library.download', 'تحميل'),
('ar', 'library.no_custom_songs_title', 'لا توجد أغاني مخصصة بعد.'),
('ar', 'library.no_custom_songs_description', 'اطلب أغنيتك الخاصة وشاهدها هنا عندما تصبح جاهزة.'),
('ar', 'library.your_custom_song', 'أغنيتك المخصصة'),
('ar', 'library.download_lyrics', '📄 تحميل الكلمات'),
('ar', 'library.download_audio', '🎵 تحميل الصوت'),
('ar', 'library.created_on', 'تم الإنشاء في'),
('ar', 'library.no_requests_title', 'لا توجد طلبات مخصصة بعد'),
('ar', 'library.no_requests_description', 'ابدأ بطلب أغنيتك المخصصة الأولى. سيعمل فريقنا عليها وستشاهد التحديثات هنا.'),
('ar', 'library.request_first_song', 'طلب الأغنية الأولى'),
('ar', 'library.requested_on', 'تم الطلب في'),

-- Chinese
('zh', 'library.title', '我的图书馆'),
('zh', 'library.description', '跟踪您的定制歌曲请求并访问您已完成的歌曲。'),
('zh', 'library.loading', '正在加载您的图书馆...'),
('zh', 'library.back_to_home', '返回主页'),
('zh', 'library.my_songs', '我的歌曲'),
('zh', 'library.custom_songs', '🎁 定制歌曲'),
('zh', 'library.my_requests', '我的请求'),
('zh', 'library.no_songs_title', '还没有歌曲'),
('zh', 'library.no_songs_description', '您还没有购买任何歌曲。从探索我们的图书馆或请求定制歌曲开始。'),
('zh', 'library.browse_songs', '浏览歌曲'),
('zh', 'library.request_custom_song', '请求定制歌曲'),
('zh', 'library.purchased_on', '购买于'),
('zh', 'library.view', '查看'),
('zh', 'library.download', '下载'),
('zh', 'library.no_custom_songs_title', '还没有定制歌曲。'),
('zh', 'library.no_custom_songs_description', '请求您自己的歌曲，准备好时在这里查看。'),
('zh', 'library.your_custom_song', '您的定制歌曲'),
('zh', 'library.download_lyrics', '📄 下载歌词'),
('zh', 'library.download_audio', '🎵 下载音频'),
('zh', 'library.created_on', '创建于'),
('zh', 'library.no_requests_title', '还没有定制请求'),
('zh', 'library.no_requests_description', '从请求您的第一首定制歌曲开始。我们的团队将为您制作，您将在这里看到更新。'),
('zh', 'library.request_first_song', '请求第一首歌曲'),
('zh', 'library.requested_on', '请求于'),

-- Hindi
('hi', 'library.title', 'मेरी लाइब्रेरी'),
('hi', 'library.description', 'अपने कस्टम गाने के अनुरोधों को ट्रैक करें और अपने पूर्ण गाने तक पहुंचें।'),
('hi', 'library.loading', 'आपकी लाइब्रेरी लोड हो रही है...'),
('hi', 'library.back_to_home', 'होम पर वापस जाएं'),
('hi', 'library.my_songs', 'मेरे गाने'),
('hi', 'library.custom_songs', '🎁 कस्टम गाने'),
('hi', 'library.my_requests', 'मेरे अनुरोध'),
('hi', 'library.no_songs_title', 'अभी तक कोई गाने नहीं'),
('hi', 'library.no_songs_description', 'आपने अभी तक कोई गाने नहीं खरीदे हैं। हमारी लाइब्रेरी एक्सप्लोर करके या कस्टम गाने का अनुरोध करके शुरुआत करें।'),
('hi', 'library.browse_songs', 'गाने ब्राउज़ करें'),
('hi', 'library.request_custom_song', 'कस्टम गाने का अनुरोध करें'),
('hi', 'library.purchased_on', 'खरीदा गया'),
('hi', 'library.view', 'देखें'),
('hi', 'library.download', 'डाउनलोड करें'),
('hi', 'library.no_custom_songs_title', 'अभी तक कोई कस्टम गाने नहीं।'),
('hi', 'library.no_custom_songs_description', 'अपना गाना अनुरोध करें और तैयार होने पर यहाँ देखें।'),
('hi', 'library.your_custom_song', 'आपका कस्टम गाना'),
('hi', 'library.download_lyrics', '📄 बोल डाउनलोड करें'),
('hi', 'library.download_audio', '🎵 ऑडियो डाउनलोड करें'),
('hi', 'library.created_on', 'बनाया गया'),
('hi', 'library.no_requests_title', 'अभी तक कोई कस्टम अनुरोध नहीं'),
('hi', 'library.no_requests_description', 'अपने पहले कस्टम गाने का अनुरोध करके शुरुआत करें। हमारी टीम इस पर काम करेगी और आपको यहाँ अपडेट दिखेंगे।'),
('hi', 'library.request_first_song', 'पहला गाना अनुरोध करें'),
('hi', 'library.requested_on', 'अनुरोध किया गया'),

-- Swahili
('sw', 'library.title', 'Maktaba Yangu'),
('sw', 'library.description', 'Fuatilia maombi yako ya nyimbo za kibinafsi na ufikie nyimbo zako zilizokamilika.'),
('sw', 'library.loading', 'Inapakia maktaba yako...'),
('sw', 'library.back_to_home', 'Rudi Nyumbani'),
('sw', 'library.my_songs', 'Nyimbo Zangu'),
('sw', 'library.custom_songs', '🎁 Nyimbo za Kibinafsi'),
('sw', 'library.my_requests', 'Maombi Yangu'),
('sw', 'library.no_songs_title', 'Hakuna Nyimbo Bado'),
('sw', 'library.no_songs_description', 'Bado hujamunua nyimbo zoyote. Anza kwa kuchunguza maktaba yetu au kuomba wimbo wa kibinafsi.'),
('sw', 'library.browse_songs', 'Vinjari Nyimbo'),
('sw', 'library.request_custom_song', 'Omba Wimbo wa Kibinafsi'),
('sw', 'library.purchased_on', 'Imenunuliwa mnamo'),
('sw', 'library.view', 'Angalia'),
('sw', 'library.download', 'Pakua'),
('sw', 'library.no_custom_songs_title', 'Hakuna nyimbo za kibinafsi bado.'),
('sw', 'library.no_custom_songs_description', 'Omba wimbo wako mwenyewe na uone hapa ukiwa tayari.'),
('sw', 'library.your_custom_song', 'Wimbo Wako wa Kibinafsi'),
('sw', 'library.download_lyrics', '📄 Pakua Maneno'),
('sw', 'library.download_audio', '🎵 Pakua Sauti'),
('sw', 'library.created_on', 'Ilitengenezwa mnamo'),
('sw', 'library.no_requests_title', 'Hakuna Maombi ya Kibinafsi Bado'),
('sw', 'library.no_requests_description', 'Anza kwa kuomba wimbo wako wa kwanza wa kibinafsi. Timu yetu itafanya kazi juu yake na utaona masasisho hapa.'),
('sw', 'library.request_first_song', 'Omba Wimbo wa Kwanza'),
('sw', 'library.requested_on', 'Imeombwa mnamo');