-- Add Navigation translations
INSERT INTO app_translations (language, key, value) VALUES
-- English
('en', 'app.title', 'Zamar'),
('en', 'nav.account', 'Account'),
('en', 'nav.profile', 'Profile'),
('en', 'nav.dashboard', 'Dashboard'),
('en', 'nav.home', 'Home'),
('en', 'nav.songs', 'Songs'),
('en', 'nav.radio', 'Radio'),
('en', 'nav.library', 'Library'),
('en', 'nav.menu', 'Menu'),
('en', 'auth.signin', 'Sign In'),
('en', 'auth.signout', 'Sign Out'),

-- French
('fr', 'app.title', 'Zamar'),
('fr', 'nav.account', 'Compte'),
('fr', 'nav.profile', 'Profil'),
('fr', 'nav.dashboard', 'Tableau de Bord'),
('fr', 'nav.home', 'Accueil'),
('fr', 'nav.songs', 'Chansons'),
('fr', 'nav.radio', 'Radio'),
('fr', 'nav.library', 'Bibliothèque'),
('fr', 'nav.menu', 'Menu'),
('fr', 'auth.signin', 'Se Connecter'),
('fr', 'auth.signout', 'Se Déconnecter'),

-- Spanish
('es', 'app.title', 'Zamar'),
('es', 'nav.account', 'Cuenta'),
('es', 'nav.profile', 'Perfil'),
('es', 'nav.dashboard', 'Panel'),
('es', 'nav.home', 'Inicio'),
('es', 'nav.songs', 'Canciones'),
('es', 'nav.radio', 'Radio'),
('es', 'nav.library', 'Biblioteca'),
('es', 'nav.menu', 'Menú'),
('es', 'auth.signin', 'Iniciar Sesión'),
('es', 'auth.signout', 'Cerrar Sesión'),

-- German
('de', 'app.title', 'Zamar'),
('de', 'nav.account', 'Konto'),
('de', 'nav.profile', 'Profil'),
('de', 'nav.dashboard', 'Dashboard'),
('de', 'nav.home', 'Startseite'),
('de', 'nav.songs', 'Songs'),
('de', 'nav.radio', 'Radio'),
('de', 'nav.library', 'Bibliothek'),
('de', 'nav.menu', 'Menü'),
('de', 'auth.signin', 'Anmelden'),
('de', 'auth.signout', 'Abmelden'),

-- Portuguese
('pt', 'app.title', 'Zamar'),
('pt', 'nav.account', 'Conta'),
('pt', 'nav.profile', 'Perfil'),
('pt', 'nav.dashboard', 'Painel'),
('pt', 'nav.home', 'Início'),
('pt', 'nav.songs', 'Músicas'),
('pt', 'nav.radio', 'Rádio'),
('pt', 'nav.library', 'Biblioteca'),
('pt', 'nav.menu', 'Menu'),
('pt', 'auth.signin', 'Entrar'),
('pt', 'auth.signout', 'Sair'),

-- Italian
('it', 'app.title', 'Zamar'),
('it', 'nav.account', 'Account'),
('it', 'nav.profile', 'Profilo'),
('it', 'nav.dashboard', 'Dashboard'),
('it', 'nav.home', 'Home'),
('it', 'nav.songs', 'Canzoni'),
('it', 'nav.radio', 'Radio'),
('it', 'nav.library', 'Biblioteca'),
('it', 'nav.menu', 'Menu'),
('it', 'auth.signin', 'Accedi'),
('it', 'auth.signout', 'Disconnetti'),

-- Arabic
('ar', 'app.title', 'زمار'),
('ar', 'nav.account', 'الحساب'),
('ar', 'nav.profile', 'الملف الشخصي'),
('ar', 'nav.dashboard', 'لوحة التحكم'),
('ar', 'nav.home', 'الرئيسية'),
('ar', 'nav.songs', 'الأغاني'),
('ar', 'nav.radio', 'الراديو'),
('ar', 'nav.library', 'المكتبة'),
('ar', 'nav.menu', 'القائمة'),
('ar', 'auth.signin', 'تسجيل الدخول'),
('ar', 'auth.signout', 'تسجيل الخروج'),

-- Chinese
('zh', 'app.title', 'Zamar'),
('zh', 'nav.account', '账户'),
('zh', 'nav.profile', '个人资料'),
('zh', 'nav.dashboard', '仪表板'),
('zh', 'nav.home', '首页'),
('zh', 'nav.songs', '歌曲'),
('zh', 'nav.radio', '电台'),
('zh', 'nav.library', '资料库'),
('zh', 'nav.menu', '菜单'),
('zh', 'auth.signin', '登录'),
('zh', 'auth.signout', '退出'),

-- Hindi
('hi', 'app.title', 'ज़मार'),
('hi', 'nav.account', 'खाता'),
('hi', 'nav.profile', 'प्रोफ़ाइल'),
('hi', 'nav.dashboard', 'डैशबोर्ड'),
('hi', 'nav.home', 'मुख्य'),
('hi', 'nav.songs', 'गाने'),
('hi', 'nav.radio', 'रेडियो'),
('hi', 'nav.library', 'लाइब्रेरी'),
('hi', 'nav.menu', 'मेनू'),
('hi', 'auth.signin', 'साइन इन'),
('hi', 'auth.signout', 'साइन आउट'),

-- Swahili
('sw', 'app.title', 'Zamar'),
('sw', 'nav.account', 'Akaunti'),
('sw', 'nav.profile', 'Wasifu'),
('sw', 'nav.dashboard', 'Dashibodi'),
('sw', 'nav.home', 'Nyumbani'),
('sw', 'nav.songs', 'Nyimbo'),
('sw', 'nav.radio', 'Redio'),
('sw', 'nav.library', 'Maktaba'),
('sw', 'nav.menu', 'Menyu'),
('sw', 'auth.signin', 'Ingia'),
('sw', 'auth.signout', 'Ondoka');