INSERT INTO app_translations (language, key, value) VALUES 
-- Pricing page translations
('en', 'pricing.choose_your', 'Choose Your'),
('en', 'pricing.perfect_package', 'Perfect Package'),
('en', 'pricing.description', 'Every song is crafted with care, love, and faith. Select the package that best fits your needs and occasion.'),
('en', 'pricing.custom_song_packages', 'Custom Song Packages'),
('en', 'pricing.personalized_songs', 'Personalized songs created just for you'),
('en', 'pricing.supporter_plans', 'Supporter & Subscription Plans'),
('en', 'pricing.ongoing_access', 'Ongoing access to our complete music library and exclusive content'),
('en', 'pricing.additional_services', 'Additional Services'),
('en', 'pricing.support_ministry', 'Support Our Ministry'),
('en', 'pricing.ministry_description', 'Help us continue creating faith-based music, supporting translation projects, and spreading the Gospel through music worldwide.'),
('en', 'pricing.give_now', 'Give Now'),
('en', 'pricing.monthly_giving', 'Monthly Giving'),
('en', 'pricing.faith_based_platform', 'Faith-Based Platform'),
('en', 'pricing.faith_notice', 'We are a Christian-led platform committed to creating meaningful music that honors our values. We may respectfully decline songs that conflict with our Christian principles, including content that promotes hate, profanity, violence, or anti-biblical messages.'),

-- Portuguese
('pt', 'pricing.choose_your', 'Escolha Seu'),
('pt', 'pricing.perfect_package', 'Pacote Perfeito'),
('pt', 'pricing.description', 'Cada música é criada com cuidado, amor e fé. Selecione o pacote que melhor se adapta às suas necessidades e ocasião.'),
('pt', 'pricing.custom_song_packages', 'Pacotes de Músicas Personalizadas'),
('pt', 'pricing.personalized_songs', 'Músicas personalizadas criadas apenas para você'),
('pt', 'pricing.supporter_plans', 'Planos de Apoiador e Assinatura'),
('pt', 'pricing.ongoing_access', 'Acesso contínuo à nossa biblioteca musical completa e conteúdo exclusivo'),
('pt', 'pricing.additional_services', 'Serviços Adicionais'),
('pt', 'pricing.support_ministry', 'Apoie Nosso Ministério'),
('pt', 'pricing.ministry_description', 'Ajude-nos a continuar criando música baseada na fé, apoiando projetos de tradução e espalhando o Evangelho através da música pelo mundo.'),
('pt', 'pricing.give_now', 'Doar Agora'),
('pt', 'pricing.monthly_giving', 'Doação Mensal'),
('pt', 'pricing.faith_based_platform', 'Plataforma Baseada na Fé'),
('pt', 'pricing.faith_notice', 'Somos uma plataforma liderada por cristãos comprometida em criar música significativa que honra nossos valores. Podemos declinar respeitosamente músicas que conflitem com nossos princípios cristãos, incluindo conteúdo que promova ódio, profanidade, violência ou mensagens anti-bíblicas.'),

-- Spanish
('es', 'pricing.choose_your', 'Elige Tu'),
('es', 'pricing.perfect_package', 'Paquete Perfecto'),
('es', 'pricing.description', 'Cada canción está creada con cuidado, amor y fe. Selecciona el paquete que mejor se adapte a tus necesidades y ocasión.'),
('es', 'pricing.custom_song_packages', 'Paquetes de Canciones Personalizadas'),
('es', 'pricing.personalized_songs', 'Canciones personalizadas creadas solo para ti'),
('es', 'pricing.supporter_plans', 'Planes de Suscriptor y Suscripción'),
('es', 'pricing.ongoing_access', 'Acceso continuo a nuestra biblioteca musical completa y contenido exclusivo'),
('es', 'pricing.additional_services', 'Servicios Adicionales'),
('es', 'pricing.support_ministry', 'Apoya Nuestro Ministerio'),
('es', 'pricing.ministry_description', 'Ayúdanos a continuar creando música basada en la fe, apoyando proyectos de traducción y difundiendo el Evangelio a través de la música en todo el mundo.'),
('es', 'pricing.give_now', 'Donar Ahora'),
('es', 'pricing.monthly_giving', 'Donación Mensual'),
('es', 'pricing.faith_based_platform', 'Plataforma Basada en la Fe'),
('es', 'pricing.faith_notice', 'Somos una plataforma dirigida por cristianos comprometida con la creación de música significativa que honra nuestros valores. Podemos declinar respetuosamente canciones que entren en conflicto con nuestros principios cristianos, incluyendo contenido que promueva odio, blasfemias, violencia o mensajes anti-bíblicos.'),

-- French
('fr', 'pricing.choose_your', 'Choisissez Votre'),
('fr', 'pricing.perfect_package', 'Package Parfait'),
('fr', 'pricing.description', 'Chaque chanson est créée avec soin, amour et foi. Sélectionnez le package qui correspond le mieux à vos besoins et à votre occasion.'),
('fr', 'pricing.custom_song_packages', 'Packages de Chansons Personnalisées'),
('fr', 'pricing.personalized_songs', 'Chansons personnalisées créées juste pour vous'),
('fr', 'pricing.supporter_plans', 'Plans de Supporter et d''Abonnement'),
('fr', 'pricing.ongoing_access', 'Accès continu à notre bibliothèque musicale complète et contenu exclusif'),
('fr', 'pricing.additional_services', 'Services Supplémentaires'),
('fr', 'pricing.support_ministry', 'Soutenez Notre Ministère'),
('fr', 'pricing.ministry_description', 'Aidez-nous à continuer de créer de la musique basée sur la foi, en soutenant les projets de traduction et en répandant l''Évangile à travers la musique dans le monde entier.'),
('fr', 'pricing.give_now', 'Donner Maintenant'),
('fr', 'pricing.monthly_giving', 'Don Mensuel'),
('fr', 'pricing.faith_based_platform', 'Plateforme Basée sur la Foi'),
('fr', 'pricing.faith_notice', 'Nous sommes une plateforme dirigée par des chrétiens engagés à créer de la musique significative qui honore nos valeurs. Nous pouvons décliner respectueusement les chansons qui sont en conflit avec nos principes chrétiens, y compris le contenu qui promeut la haine, les blasphèmes, la violence ou les messages anti-bibliques.'),

-- German
('de', 'pricing.choose_your', 'Wählen Sie Ihr'),
('de', 'pricing.perfect_package', 'Perfektes Paket'),
('de', 'pricing.description', 'Jedes Lied wird mit Sorgfalt, Liebe und Glauben erstellt. Wählen Sie das Paket, das am besten zu Ihren Bedürfnissen und Ihrem Anlass passt.'),
('de', 'pricing.custom_song_packages', 'Personalisierte Lied-Pakete'),
('de', 'pricing.personalized_songs', 'Personalisierte Lieder nur für Sie erstellt'),
('de', 'pricing.supporter_plans', 'Unterstützer- und Abonnement-Pläne'),
('de', 'pricing.ongoing_access', 'Fortlaufender Zugang zu unserer kompletten Musikbibliothek und exklusiven Inhalten'),
('de', 'pricing.additional_services', 'Zusätzliche Dienste'),
('de', 'pricing.support_ministry', 'Unterstützen Sie Unser Ministerium'),
('de', 'pricing.ministry_description', 'Helfen Sie uns dabei, weiterhin glaubensbasierte Musik zu schaffen, Übersetzungsprojekte zu unterstützen und das Evangelium durch Musik weltweit zu verbreiten.'),
('de', 'pricing.give_now', 'Jetzt Spenden'),
('de', 'pricing.monthly_giving', 'Monatliche Spende'),
('de', 'pricing.faith_based_platform', 'Glaubensbasierte Plattform'),
('de', 'pricing.faith_notice', 'Wir sind eine von Christen geführte Plattform, die sich der Schaffung bedeutungsvoller Musik verschrieben hat, die unsere Werte ehrt. Wir können Lieder respektvoll ablehnen, die mit unseren christlichen Grundsätzen in Konflikt stehen, einschließlich Inhalten, die Hass, Gotteslästerung, Gewalt oder anti-biblische Botschaften fördern.');