-- Add translations for Terms & Conditions page
INSERT INTO app_translations (language, key, value) VALUES 
-- English translations for Terms page
('en', 'terms.title', 'Terms & Conditions'),
('en', 'terms.effective_date', 'Effective Date: December 1, 2024'),
('en', 'terms.acceptance.title', '1. Acceptance of Terms'),
('en', 'terms.acceptance.content', 'By accessing and using Zamar, you accept and agree to be bound by the terms and provision of this agreement.'),
('en', 'terms.use_license.title', '2. Use License'),
('en', 'terms.use_license.content', 'Permission is granted to temporarily download one copy of the materials on Zamar for personal, non-commercial transitory viewing only.'),
('en', 'terms.user_content.title', '3. User Content'),
('en', 'terms.user_content.content', 'Users may submit content including song requests and testimonies. By submitting content, you grant us a non-exclusive license to use, modify, and display such content.'),
('en', 'terms.faith_policy.title', '4. Faith-Based Content Policy'),
('en', 'terms.faith_policy.content', 'Zamar is a Christian platform. Content that conflicts with biblical principles may be declined. We reserve the right to review and moderate all submissions.'),
('en', 'terms.disclaimer.title', '5. Disclaimer'),
('en', 'terms.disclaimer.content', 'The materials on Zamar are provided on an ''as is'' basis. Zamar makes no warranties, expressed or implied, and disclaims all other warranties.'),
('en', 'terms.limitations.title', '6. Limitations'),
('en', 'terms.limitations.content', 'In no event shall Zamar be liable for any damages arising out of the use or inability to use the materials on our platform.'),
('en', 'terms.accuracy.title', '7. Accuracy of Materials'),
('en', 'terms.accuracy.content', 'The materials appearing on Zamar could include technical, typographical, or photographic errors. We do not warrant accuracy.'),
('en', 'terms.links.title', '8. Links'),
('en', 'terms.links.content', 'Zamar has not reviewed all sites linked to our platform and is not responsible for the contents of any linked site.'),
('en', 'terms.modifications.title', '9. Modifications'),
('en', 'terms.modifications.content', 'Zamar may revise these terms at any time without notice. By using this platform, you agree to be bound by the current version.'),
('en', 'terms.governing_law.title', '10. Governing Law'),
('en', 'terms.governing_law.content', 'These terms are governed by and construed in accordance with applicable laws.'),
('en', 'terms.contact.title', 'Contact Information'),
('en', 'terms.contact.content', 'If you have any questions about these Terms & Conditions, please contact us at support@zamar.com'),

-- Spanish translations for Terms page
('es', 'terms.title', 'Términos y Condiciones'),
('es', 'terms.effective_date', 'Fecha de vigencia: 1 de diciembre de 2024'),
('es', 'terms.acceptance.title', '1. Aceptación de Términos'),
('es', 'terms.acceptance.content', 'Al acceder y usar Zamar, acepta y acuerda estar sujeto a los términos y disposiciones de este acuerdo.'),
('es', 'terms.use_license.title', '2. Licencia de Uso'),
('es', 'terms.use_license.content', 'Se otorga permiso para descargar temporalmente una copia de los materiales en Zamar solo para visualización personal y no comercial.'),
('es', 'terms.user_content.title', '3. Contenido del Usuario'),
('es', 'terms.user_content.content', 'Los usuarios pueden enviar contenido incluyendo solicitudes de canciones y testimonios. Al enviar contenido, nos otorga una licencia no exclusiva para usar, modificar y mostrar dicho contenido.'),
('es', 'terms.faith_policy.title', '4. Política de Contenido Basado en Fe'),
('es', 'terms.faith_policy.content', 'Zamar es una plataforma cristiana. El contenido que entre en conflicto con los principios bíblicos puede ser rechazado. Nos reservamos el derecho de revisar y moderar todas las presentaciones.'),
('es', 'terms.disclaimer.title', '5. Descargo de Responsabilidad'),
('es', 'terms.disclaimer.content', 'Los materiales en Zamar se proporcionan ''tal como están''. Zamar no ofrece garantías, expresas o implícitas, y renuncia a todas las demás garantías.'),
('es', 'terms.limitations.title', '6. Limitaciones'),
('es', 'terms.limitations.content', 'En ningún caso Zamar será responsable por daños que surjan del uso o la incapacidad de usar los materiales en nuestra plataforma.'),
('es', 'terms.accuracy.title', '7. Precisión de Materiales'),
('es', 'terms.accuracy.content', 'Los materiales que aparecen en Zamar podrían incluir errores técnicos, tipográficos o fotográficos. No garantizamos la precisión.'),
('es', 'terms.links.title', '8. Enlaces'),
('es', 'terms.links.content', 'Zamar no ha revisado todos los sitios vinculados a nuestra plataforma y no es responsable del contenido de ningún sitio vinculado.'),
('es', 'terms.modifications.title', '9. Modificaciones'),
('es', 'terms.modifications.content', 'Zamar puede revisar estos términos en cualquier momento sin previo aviso. Al usar esta plataforma, acepta estar sujeto a la versión actual.'),
('es', 'terms.governing_law.title', '10. Ley Aplicable'),
('es', 'terms.governing_law.content', 'Estos términos se rigen e interpretan de acuerdo con las leyes aplicables.'),
('es', 'terms.contact.title', 'Información de Contacto'),
('es', 'terms.contact.content', 'Si tiene alguna pregunta sobre estos Términos y Condiciones, contáctenos en support@zamar.com');