-- Add Library page translations
INSERT INTO app_translations (language, key, value) VALUES
-- English
('en', 'library.title', 'My Library'),
('en', 'library.subtitle', 'Track your custom song requests and access your completed songs.'),
('en', 'library.backToHome', 'Back to Home'),
('en', 'library.loading', 'Loading your library...'),
('en', 'library.tabs.mySongs', 'My Songs'),
('en', 'library.tabs.customSongs', 'Custom Songs'),
('en', 'library.tabs.myRequests', 'My Requests'),
('en', 'library.noSongsYet', 'No Songs Yet'),
('en', 'library.noSongsDescription', 'You haven''t purchased any songs yet. Start by exploring our library or requesting a custom song.'),
('en', 'library.browseSongs', 'Browse Songs'),
('en', 'library.requestCustomSong', 'Request Custom Song'),
('en', 'library.purchasedOn', 'Purchased on'),
('en', 'library.view', 'View'),
('en', 'library.download', 'Download'),
('en', 'library.noCustomSongs', 'No custom songs yet.'),
('en', 'library.noCustomSongsDescription', 'Request your own song and see it here when ready.'),
('en', 'library.yourCustomSong', 'Your Custom Song'),
('en', 'library.downloadLyrics', 'Download Lyrics'),
('en', 'library.noRequestsYet', 'No requests yet'),
('en', 'library.noRequestsDescription', 'You haven''t made any custom song requests yet. Create your first request to get started.'),
('en', 'library.occasion', 'Occasion'),
('en', 'library.genre', 'Genre'),
('en', 'library.tier', 'Tier'),
('en', 'library.requestedOn', 'Requested on'),
('en', 'library.viewRequest', 'View Request'),
('en', 'library.delivered', 'Delivered'),
('en', 'library.created', 'Created'),
('en', 'library.pending', 'Pending'),

-- French
('fr', 'library.title', 'Ma Bibliothèque'),
('fr', 'library.subtitle', 'Suivez vos demandes de chansons personnalisées et accédez à vos chansons terminées.'),
('fr', 'library.backToHome', 'Retour à l''Accueil'),
('fr', 'library.loading', 'Chargement de votre bibliothèque...'),
('fr', 'library.tabs.mySongs', 'Mes Chansons'),
('fr', 'library.tabs.customSongs', 'Chansons Personnalisées'),
('fr', 'library.tabs.myRequests', 'Mes Demandes'),
('fr', 'library.noSongsYet', 'Aucune Chanson Encore'),
('fr', 'library.noSongsDescription', 'Vous n''avez encore acheté aucune chanson. Commencez par explorer notre bibliothèque ou demander une chanson personnalisée.'),
('fr', 'library.browseSongs', 'Parcourir les Chansons'),
('fr', 'library.requestCustomSong', 'Demander une Chanson Personnalisée'),
('fr', 'library.purchasedOn', 'Acheté le'),
('fr', 'library.view', 'Voir'),
('fr', 'library.download', 'Télécharger'),
('fr', 'library.noCustomSongs', 'Aucune chanson personnalisée encore.'),
('fr', 'library.noCustomSongsDescription', 'Demandez votre propre chanson et voyez-la ici quand elle sera prête.'),
('fr', 'library.yourCustomSong', 'Votre Chanson Personnalisée'),
('fr', 'library.downloadLyrics', 'Télécharger les Paroles'),
('fr', 'library.noRequestsYet', 'Aucune demande encore'),
('fr', 'library.noRequestsDescription', 'Vous n''avez encore fait aucune demande de chanson personnalisée. Créez votre première demande pour commencer.'),
('fr', 'library.occasion', 'Occasion'),
('fr', 'library.genre', 'Genre'),
('fr', 'library.tier', 'Niveau'),
('fr', 'library.requestedOn', 'Demandé le'),
('fr', 'library.viewRequest', 'Voir la Demande'),
('fr', 'library.delivered', 'Livré'),
('fr', 'library.created', 'Créé'),
('fr', 'library.pending', 'En Attente'),

-- Spanish
('es', 'library.title', 'Mi Biblioteca'),
('es', 'library.subtitle', 'Rastrea tus solicitudes de canciones personalizadas y accede a tus canciones completadas.'),
('es', 'library.backToHome', 'Volver al Inicio'),
('es', 'library.loading', 'Cargando tu biblioteca...'),
('es', 'library.tabs.mySongs', 'Mis Canciones'),
('es', 'library.tabs.customSongs', 'Canciones Personalizadas'),
('es', 'library.tabs.myRequests', 'Mis Solicitudes'),
('es', 'library.noSongsYet', 'Aún No Hay Canciones'),
('es', 'library.noSongsDescription', 'Aún no has comprado ninguna canción. Comienza explorando nuestra biblioteca o solicitando una canción personalizada.'),
('es', 'library.browseSongs', 'Explorar Canciones'),
('es', 'library.requestCustomSong', 'Solicitar Canción Personalizada'),
('es', 'library.purchasedOn', 'Comprado el'),
('es', 'library.view', 'Ver'),
('es', 'library.download', 'Descargar'),
('es', 'library.noCustomSongs', 'Aún no hay canciones personalizadas.'),
('es', 'library.noCustomSongsDescription', 'Solicita tu propia canción y la verás aquí cuando esté lista.'),
('es', 'library.yourCustomSong', 'Tu Canción Personalizada'),
('es', 'library.downloadLyrics', 'Descargar Letras'),
('es', 'library.noRequestsYet', 'Aún no hay solicitudes'),
('es', 'library.noRequestsDescription', 'Aún no has hecho ninguna solicitud de canción personalizada. Crea tu primera solicitud para comenzar.'),
('es', 'library.occasion', 'Ocasión'),
('es', 'library.genre', 'Género'),
('es', 'library.tier', 'Nivel'),
('es', 'library.requestedOn', 'Solicitado el'),
('es', 'library.viewRequest', 'Ver Solicitud'),
('es', 'library.delivered', 'Entregado'),
('es', 'library.created', 'Creado'),
('es', 'library.pending', 'Pendiente'),

-- German
('de', 'library.title', 'Meine Bibliothek'),
('de', 'library.subtitle', 'Verfolgen Sie Ihre benutzerdefinierten Song-Anfragen und greifen Sie auf Ihre fertigen Songs zu.'),
('de', 'library.backToHome', 'Zurück zur Startseite'),
('de', 'library.loading', 'Ihre Bibliothek wird geladen...'),
('de', 'library.tabs.mySongs', 'Meine Songs'),
('de', 'library.tabs.customSongs', 'Benutzerdefinierte Songs'),
('de', 'library.tabs.myRequests', 'Meine Anfragen'),
('de', 'library.noSongsYet', 'Noch Keine Songs'),
('de', 'library.noSongsDescription', 'Sie haben noch keine Songs gekauft. Beginnen Sie mit der Erkundung unserer Bibliothek oder fordern Sie einen benutzerdefinierten Song an.'),
('de', 'library.browseSongs', 'Songs Durchsuchen'),
('de', 'library.requestCustomSong', 'Benutzerdefinierten Song Anfordern'),
('de', 'library.purchasedOn', 'Gekauft am'),
('de', 'library.view', 'Ansehen'),
('de', 'library.download', 'Herunterladen'),
('de', 'library.noCustomSongs', 'Noch keine benutzerdefinierten Songs.'),
('de', 'library.noCustomSongsDescription', 'Fordern Sie Ihren eigenen Song an und sehen Sie ihn hier, wenn er fertig ist.'),
('de', 'library.yourCustomSong', 'Ihr Benutzerdefinierter Song'),
('de', 'library.downloadLyrics', 'Texte Herunterladen'),
('de', 'library.noRequestsYet', 'Noch keine Anfragen'),
('de', 'library.noRequestsDescription', 'Sie haben noch keine benutzerdefinierten Song-Anfragen gestellt. Erstellen Sie Ihre erste Anfrage, um zu beginnen.'),
('de', 'library.occasion', 'Anlass'),
('de', 'library.genre', 'Genre'),
('de', 'library.tier', 'Stufe'),
('de', 'library.requestedOn', 'Angefordert am'),
('de', 'library.viewRequest', 'Anfrage Ansehen'),
('de', 'library.delivered', 'Geliefert'),
('de', 'library.created', 'Erstellt'),
('de', 'library.pending', 'Ausstehend'),

-- Portuguese
('pt', 'library.title', 'Minha Biblioteca'),
('pt', 'library.subtitle', 'Acompanhe suas solicitações de músicas personalizadas e acesse suas músicas concluídas.'),
('pt', 'library.backToHome', 'Voltar ao Início'),
('pt', 'library.loading', 'Carregando sua biblioteca...'),
('pt', 'library.tabs.mySongs', 'Minhas Músicas'),
('pt', 'library.tabs.customSongs', 'Músicas Personalizadas'),
('pt', 'library.tabs.myRequests', 'Minhas Solicitações'),
('pt', 'library.noSongsYet', 'Ainda Não Há Músicas'),
('pt', 'library.noSongsDescription', 'Você ainda não comprou nenhuma música. Comece explorando nossa biblioteca ou solicitando uma música personalizada.'),
('pt', 'library.browseSongs', 'Explorar Músicas'),
('pt', 'library.requestCustomSong', 'Solicitar Música Personalizada'),
('pt', 'library.purchasedOn', 'Comprado em'),
('pt', 'library.view', 'Ver'),
('pt', 'library.download', 'Baixar'),
('pt', 'library.noCustomSongs', 'Ainda não há músicas personalizadas.'),
('pt', 'library.noCustomSongsDescription', 'Solicite sua própria música e a veja aqui quando estiver pronta.'),
('pt', 'library.yourCustomSong', 'Sua Música Personalizada'),
('pt', 'library.downloadLyrics', 'Baixar Letras'),
('pt', 'library.noRequestsYet', 'Ainda não há solicitações'),
('pt', 'library.noRequestsDescription', 'Você ainda não fez nenhuma solicitação de música personalizada. Crie sua primeira solicitação para começar.'),
('pt', 'library.occasion', 'Ocasião'),
('pt', 'library.genre', 'Gênero'),
('pt', 'library.tier', 'Nível'),
('pt', 'library.requestedOn', 'Solicitado em'),
('pt', 'library.viewRequest', 'Ver Solicitação'),
('pt', 'library.delivered', 'Entregue'),
('pt', 'library.created', 'Criado'),
('pt', 'library.pending', 'Pendente'),

-- Italian
('it', 'library.title', 'La Mia Biblioteca'),
('it', 'library.subtitle', 'Traccia le tue richieste di canzoni personalizzate e accedi alle tue canzoni completate.'),
('it', 'library.backToHome', 'Torna alla Home'),
('it', 'library.loading', 'Caricamento della tua biblioteca...'),
('it', 'library.tabs.mySongs', 'Le Mie Canzoni'),
('it', 'library.tabs.customSongs', 'Canzoni Personalizzate'),
('it', 'library.tabs.myRequests', 'Le Mie Richieste'),
('it', 'library.noSongsYet', 'Ancora Nessuna Canzone'),
('it', 'library.noSongsDescription', 'Non hai ancora acquistato nessuna canzone. Inizia esplorando la nostra biblioteca o richiedendo una canzone personalizzata.'),
('it', 'library.browseSongs', 'Sfoglia Canzoni'),
('it', 'library.requestCustomSong', 'Richiedi Canzone Personalizzata'),
('it', 'library.purchasedOn', 'Acquistato il'),
('it', 'library.view', 'Visualizza'),
('it', 'library.download', 'Scarica'),
('it', 'library.noCustomSongs', 'Ancora nessuna canzone personalizzata.'),
('it', 'library.noCustomSongsDescription', 'Richiedi la tua canzone e la vedrai qui quando sarà pronta.'),
('it', 'library.yourCustomSong', 'La Tua Canzone Personalizzata'),
('it', 'library.downloadLyrics', 'Scarica Testi'),
('it', 'library.noRequestsYet', 'Ancora nessuna richiesta'),
('it', 'library.noRequestsDescription', 'Non hai ancora fatto nessuna richiesta di canzone personalizzata. Crea la tua prima richiesta per iniziare.'),
('it', 'library.occasion', 'Occasione'),
('it', 'library.genre', 'Genere'),
('it', 'library.tier', 'Livello'),
('it', 'library.requestedOn', 'Richiesto il'),
('it', 'library.viewRequest', 'Visualizza Richiesta'),
('it', 'library.delivered', 'Consegnato'),
('it', 'library.created', 'Creato'),
('it', 'library.pending', 'In Attesa'),

-- Arabic  
('ar', 'library.title', 'مكتبتي'),
('ar', 'library.subtitle', 'تتبع طلبات الأغاني المخصصة الخاصة بك والوصول إلى أغانيك المكتملة.'),
('ar', 'library.backToHome', 'العودة للرئيسية'),
('ar', 'library.loading', 'جاري تحميل مكتبتك...'),
('ar', 'library.tabs.mySongs', 'أغانيي'),
('ar', 'library.tabs.customSongs', 'الأغاني المخصصة'),
('ar', 'library.tabs.myRequests', 'طلباتي'),
('ar', 'library.noSongsYet', 'لا توجد أغاني بعد'),
('ar', 'library.noSongsDescription', 'لم تشتر أي أغاني بعد. ابدأ باستكشاف مكتبتنا أو طلب أغنية مخصصة.'),
('ar', 'library.browseSongs', 'تصفح الأغاني'),
('ar', 'library.requestCustomSong', 'طلب أغنية مخصصة'),
('ar', 'library.purchasedOn', 'تم الشراء في'),
('ar', 'library.view', 'عرض'),
('ar', 'library.download', 'تحميل'),
('ar', 'library.noCustomSongs', 'لا توجد أغاني مخصصة بعد.'),
('ar', 'library.noCustomSongsDescription', 'اطلب أغنيتك الخاصة وشاهدها هنا عندما تصبح جاهزة.'),
('ar', 'library.yourCustomSong', 'أغنيتك المخصصة'),
('ar', 'library.downloadLyrics', 'تحميل كلمات'),
('ar', 'library.noRequestsYet', 'لا توجد طلبات بعد'),
('ar', 'library.noRequestsDescription', 'لم تقم بأي طلبات أغاني مخصصة بعد. أنشئ طلبك الأول للبدء.'),
('ar', 'library.occasion', 'المناسبة'),
('ar', 'library.genre', 'النوع'),
('ar', 'library.tier', 'المستوى'),
('ar', 'library.requestedOn', 'طُلب في'),
('ar', 'library.viewRequest', 'عرض الطلب'),
('ar', 'library.delivered', 'تم التسليم'),
('ar', 'library.created', 'تم الإنشاء'),
('ar', 'library.pending', 'في الانتظار'),

-- Chinese
('zh', 'library.title', '我的音乐库'),
('zh', 'library.subtitle', '跟踪您的定制歌曲请求并访问您已完成的歌曲。'),
('zh', 'library.backToHome', '返回首页'),
('zh', 'library.loading', '正在加载您的音乐库...'),
('zh', 'library.tabs.mySongs', '我的歌曲'),
('zh', 'library.tabs.customSongs', '定制歌曲'),
('zh', 'library.tabs.myRequests', '我的请求'),
('zh', 'library.noSongsYet', '还没有歌曲'),
('zh', 'library.noSongsDescription', '您还没有购买任何歌曲。从探索我们的音乐库或请求定制歌曲开始。'),
('zh', 'library.browseSongs', '浏览歌曲'),
('zh', 'library.requestCustomSong', '请求定制歌曲'),
('zh', 'library.purchasedOn', '购买于'),
('zh', 'library.view', '查看'),
('zh', 'library.download', '下载'),
('zh', 'library.noCustomSongs', '还没有定制歌曲。'),
('zh', 'library.noCustomSongsDescription', '请求您自己的歌曲，准备好后在这里查看。'),
('zh', 'library.yourCustomSong', '您的定制歌曲'),
('zh', 'library.downloadLyrics', '下载歌词'),
('zh', 'library.noRequestsYet', '还没有请求'),
('zh', 'library.noRequestsDescription', '您还没有提出任何定制歌曲请求。创建您的第一个请求以开始。'),
('zh', 'library.occasion', '场合'),
('zh', 'library.genre', '类型'),
('zh', 'library.tier', '等级'),
('zh', 'library.requestedOn', '请求于'),
('zh', 'library.viewRequest', '查看请求'),
('zh', 'library.delivered', '已交付'),
('zh', 'library.created', '已创建'),
('zh', 'library.pending', '待处理'),

-- Hindi
('hi', 'library.title', 'मेरी लाइब्रेरी'),
('hi', 'library.subtitle', 'अपने कस्टम गाने के अनुरोधों को ट्रैक करें और अपने पूर्ण गानों तक पहुंचें।'),
('hi', 'library.backToHome', 'होम पर वापस जाएं'),
('hi', 'library.loading', 'आपकी लाइब्रेरी लोड हो रही है...'),
('hi', 'library.tabs.mySongs', 'मेरे गाने'),
('hi', 'library.tabs.customSongs', 'कस्टम गाने'),
('hi', 'library.tabs.myRequests', 'मेरे अनुरोध'),
('hi', 'library.noSongsYet', 'अभी तक कोई गाने नहीं'),
('hi', 'library.noSongsDescription', 'आपने अभी तक कोई गाने नहीं खरीदे हैं। हमारी लाइब्रेरी एक्सप्लोर करके या कस्टम गाने का अनुरोध करके शुरुआत करें।'),
('hi', 'library.browseSongs', 'गाने ब्राउज़ करें'),
('hi', 'library.requestCustomSong', 'कस्टम गाने का अनुरोध करें'),
('hi', 'library.purchasedOn', 'खरीदा गया'),
('hi', 'library.view', 'देखें'),
('hi', 'library.download', 'डाउनलोड करें'),
('hi', 'library.noCustomSongs', 'अभी तक कोई कस्टम गाने नहीं।'),
('hi', 'library.noCustomSongsDescription', 'अपना गाना अनुरोध करें और तैयार होने पर यहां देखें।'),
('hi', 'library.yourCustomSong', 'आपका कस्टम गाना'),
('hi', 'library.downloadLyrics', 'बोल डाउनलोड करें'),
('hi', 'library.noRequestsYet', 'अभी तक कोई अनुरोध नहीं'),
('hi', 'library.noRequestsDescription', 'आपने अभी तक कोई कस्टम गाने के अनुरोध नहीं किए हैं। शुरुआत करने के लिए अपना पहला अनुरोध बनाएं।'),
('hi', 'library.occasion', 'अवसर'),
('hi', 'library.genre', 'शैली'),
('hi', 'library.tier', 'स्तर'),
('hi', 'library.requestedOn', 'अनुरोध किया गया'),
('hi', 'library.viewRequest', 'अनुरोध देखें'),
('hi', 'library.delivered', 'डिलीवर किया गया'),
('hi', 'library.created', 'बनाया गया'),
('hi', 'library.pending', 'लंबित'),

-- Swahili
('sw', 'library.title', 'Maktaba Yangu'),
('sw', 'library.subtitle', 'Fuatilia maombi yako ya nyimbo za kibinafsi na ufikirie nyimbo zako zilizokamilika.'),
('sw', 'library.backToHome', 'Rudi Nyumbani'),
('sw', 'library.loading', 'Inapakia maktaba yako...'),
('sw', 'library.tabs.mySongs', 'Nyimbo Zangu'),
('sw', 'library.tabs.customSongs', 'Nyimbo za Kibinafsi'),
('sw', 'library.tabs.myRequests', 'Maombi Yangu'),
('sw', 'library.noSongsYet', 'Hakuna Nyimbo Bado'),
('sw', 'library.noSongsDescription', 'Bado hujashinunua nyimbo yoyote. Anza kwa kuchunguza maktaba yetu au kuomba wimbo wa kibinafsi.'),
('sw', 'library.browseSongs', 'Vinjari Nyimbo'),
('sw', 'library.requestCustomSong', 'Omba Wimbo wa Kibinafsi'),
('sw', 'library.purchasedOn', 'Ilinunuliwa mnamo'),
('sw', 'library.view', 'Ona'),
('sw', 'library.download', 'Pakua'),
('sw', 'library.noCustomSongs', 'Hakuna nyimbo za kibinafsi bado.'),
('sw', 'library.noCustomSongsDescription', 'Omba wimbo wako na uone hapa ukiwa tayari.'),
('sw', 'library.yourCustomSong', 'Wimbo Wako wa Kibinafsi'),
('sw', 'library.downloadLyrics', 'Pakua Maneno'),
('sw', 'library.noRequestsYet', 'Hakuna maombi bado'),
('sw', 'library.noRequestsDescription', 'Bado hujafanya maombi yoyote ya nyimbo za kibinafsi. Unda ombi lako la kwanza ili kuanza.'),
('sw', 'library.occasion', 'Tukio'),
('sw', 'library.genre', 'Aina'),
('sw', 'library.tier', 'Kiwango'),
('sw', 'library.requestedOn', 'Iliombwa mnamo'),
('sw', 'library.viewRequest', 'Ona Ombi'),
('sw', 'library.delivered', 'Imepokelewa'),
('sw', 'library.created', 'Imeundwa'),
('sw', 'library.pending', 'Inasubiri');