-- Add German translations
INSERT INTO public.app_translations (language, key, value) VALUES
('de', 'app.title', 'ZAMAR'),
('de', 'nav.home', 'Startseite'),
('de', 'nav.songs', 'Lieder'),
('de', 'nav.radio', 'Radio'),
('de', 'nav.library', 'Bibliothek'),
('de', 'nav.menu', 'Menü'),
('de', 'nav.back_home', 'Zurück zur Startseite'),
('de', 'nav.account', 'Konto'),
('de', 'nav.profile', 'Profil'),
('de', 'nav.dashboard', 'Dashboard'),
('de', 'player.play', 'Abspielen'),
('de', 'player.pause', 'Pause'),
('de', 'player.next', 'Weiter'),
('de', 'player.previous', 'Zurück'),
('de', 'auth.signin', 'Anmelden'),
('de', 'auth.signup', 'Registrieren'),
('de', 'auth.welcome', 'Willkommen bei Zamar'),
('de', 'auth.subtitle', 'Melden Sie sich bei Ihrem Konto an oder erstellen Sie ein neues'),
('de', 'auth.login', 'Anmelden'),
('de', 'auth.email', 'E-Mail'),
('de', 'auth.password', 'Passwort'),
('de', 'auth.signing_in', 'Anmeldung läuft...'),
('de', 'auth.first_name', 'Vorname'),
('de', 'auth.last_name', 'Nachname'),
('de', 'auth.confirm_password', 'Passwort bestätigen'),
('de', 'auth.creating_account', 'Konto wird erstellt...'),
('de', 'auth.create_account', 'Konto erstellen'),
('de', 'auth.signout', 'Abmelden'),
('de', 'settings.language', 'Sprache'),
('de', 'common.loading', 'Wird geladen...'),
('de', 'common.error', 'Fehler aufgetreten')
ON CONFLICT (language, key) DO UPDATE SET value = EXCLUDED.value;

-- Add Portuguese translations
INSERT INTO public.app_translations (language, key, value) VALUES
('pt', 'app.title', 'ZAMAR'),
('pt', 'nav.home', 'Início'),
('pt', 'nav.songs', 'Músicas'),
('pt', 'nav.radio', 'Rádio'),
('pt', 'nav.library', 'Biblioteca'),
('pt', 'nav.menu', 'Menu'),
('pt', 'nav.back_home', 'Voltar ao início'),
('pt', 'nav.account', 'Conta'),
('pt', 'nav.profile', 'Perfil'),
('pt', 'nav.dashboard', 'Painel'),
('pt', 'player.play', 'Reproduzir'),
('pt', 'player.pause', 'Pausar'),
('pt', 'player.next', 'Próximo'),
('pt', 'player.previous', 'Anterior'),
('pt', 'auth.signin', 'Entrar'),
('pt', 'auth.signup', 'Cadastrar'),
('pt', 'auth.welcome', 'Bem-vindo ao Zamar'),
('pt', 'auth.subtitle', 'Entre em sua conta ou crie uma nova'),
('pt', 'auth.login', 'Entrar'),
('pt', 'auth.email', 'E-mail'),
('pt', 'auth.password', 'Senha'),
('pt', 'auth.signing_in', 'Entrando...'),
('pt', 'auth.first_name', 'Nome'),
('pt', 'auth.last_name', 'Sobrenome'),
('pt', 'auth.confirm_password', 'Confirmar senha'),
('pt', 'auth.creating_account', 'Criando conta...'),
('pt', 'auth.create_account', 'Criar conta'),
('pt', 'auth.signout', 'Sair'),
('pt', 'settings.language', 'Idioma'),
('pt', 'common.loading', 'Carregando...'),
('pt', 'common.error', 'Erro ocorreu')
ON CONFLICT (language, key) DO UPDATE SET value = EXCLUDED.value;

-- Add Italian translations
INSERT INTO public.app_translations (language, key, value) VALUES
('it', 'app.title', 'ZAMAR'),
('it', 'nav.home', 'Casa'),
('it', 'nav.songs', 'Canzoni'),
('it', 'nav.radio', 'Radio'),
('it', 'nav.library', 'Biblioteca'),
('it', 'nav.menu', 'Menu'),
('it', 'nav.back_home', 'Torna alla home'),
('it', 'nav.account', 'Account'),
('it', 'nav.profile', 'Profilo'),
('it', 'nav.dashboard', 'Dashboard'),
('it', 'player.play', 'Riproduci'),
('it', 'player.pause', 'Pausa'),
('it', 'player.next', 'Avanti'),
('it', 'player.previous', 'Indietro'),
('it', 'auth.signin', 'Accedi'),
('it', 'auth.signup', 'Registrati'),
('it', 'auth.welcome', 'Benvenuto in Zamar'),
('it', 'auth.subtitle', 'Accedi al tuo account o creane uno nuovo'),
('it', 'auth.login', 'Accedi'),
('it', 'auth.email', 'Email'),
('it', 'auth.password', 'Password'),
('it', 'auth.signing_in', 'Accesso in corso...'),
('it', 'auth.first_name', 'Nome'),
('it', 'auth.last_name', 'Cognome'),
('it', 'auth.confirm_password', 'Conferma password'),
('it', 'auth.creating_account', 'Creazione account...'),
('it', 'auth.create_account', 'Crea account'),
('it', 'auth.signout', 'Esci'),
('it', 'settings.language', 'Lingua'),
('it', 'common.loading', 'Caricamento...'),
('it', 'common.error', 'Errore verificato')
ON CONFLICT (language, key) DO UPDATE SET value = EXCLUDED.value;