-- Add footer translations for all languages
INSERT INTO app_translations (language, key, value) VALUES

-- Footer translations - English
('en', 'footer.description', 'Creating meaningful custom songs for every occasion. A faith-based platform dedicated to bringing your stories to life through music.'),
('en', 'footer.faith_values', 'Faith-based platform • Christian values'),
('en', 'footer.quick_links', 'Quick Links'),
('en', 'footer.about_us', 'About Us'),
('en', 'footer.song_library', 'Song Library'),
('en', 'footer.pricing', 'Pricing'),
('en', 'footer.create_song', 'Create Song'),
('en', 'footer.testimonies', 'Testimonies'),
('en', 'footer.support', 'Support'),
('en', 'footer.faq', 'FAQ'),
('en', 'footer.terms_conditions', 'Terms & Conditions'),
('en', 'footer.contact_us', 'Contact Us'),
('en', 'footer.support_mission', 'Support Our Mission'),
('en', 'footer.copyright', '© 2025 Zamar. All rights reserved.'),
('en', 'footer.faith_disclaimer', '🛐 Faith-based disclaimer: We reserve the right to decline requests that go against our Christian values.'),

-- Footer translations - German
('de', 'footer.description', 'Erstellen bedeutungsvoller individueller Lieder für jeden Anlass. Eine glaubensbasierte Plattform, die Ihre Geschichten durch Musik zum Leben erweckt.'),
('de', 'footer.faith_values', 'Glaubensbasierte Plattform • Christliche Werte'),
('de', 'footer.quick_links', 'Schnelle Links'),
('de', 'footer.about_us', 'Über uns'),
('de', 'footer.song_library', 'Liederbibliothek'),
('de', 'footer.pricing', 'Preise'),
('de', 'footer.create_song', 'Lied erstellen'),
('de', 'footer.testimonies', 'Zeugnisse'),
('de', 'footer.support', 'Support'),
('de', 'footer.faq', 'FAQ'),
('de', 'footer.terms_conditions', 'Geschäftsbedingungen'),
('de', 'footer.contact_us', 'Kontaktieren Sie uns'),
('de', 'footer.support_mission', 'Unterstützen Sie unsere Mission'),
('de', 'footer.copyright', '© 2025 Zamar. Alle Rechte vorbehalten.'),
('de', 'footer.faith_disclaimer', '🛐 Glaubensbasierter Haftungsausschluss: Wir behalten uns das Recht vor, Anfragen abzulehnen, die gegen unsere christlichen Werte verstoßen.'),

-- Footer translations - French
('fr', 'footer.description', 'Créer des chansons personnalisées significatives pour chaque occasion. Une plateforme basée sur la foi dédiée à donner vie à vos histoires à travers la musique.'),
('fr', 'footer.faith_values', 'Plateforme basée sur la foi • Valeurs chrétiennes'),
('fr', 'footer.quick_links', 'Liens rapides'),
('fr', 'footer.about_us', 'À propos de nous'),
('fr', 'footer.song_library', 'Bibliothèque de chansons'),
('fr', 'footer.pricing', 'Tarifs'),
('fr', 'footer.create_song', 'Créer une chanson'),
('fr', 'footer.testimonies', 'Témoignages'),
('fr', 'footer.support', 'Support'),
('fr', 'footer.faq', 'FAQ'),
('fr', 'footer.terms_conditions', 'Conditions générales'),
('fr', 'footer.contact_us', 'Nous contacter'),
('fr', 'footer.support_mission', 'Soutenez notre mission'),
('fr', 'footer.copyright', '© 2025 Zamar. Tous droits réservés.'),
('fr', 'footer.faith_disclaimer', '🛐 Avertissement basé sur la foi : Nous nous réservons le droit de refuser les demandes qui vont contre nos valeurs chrétiennes.'),

-- Footer translations - Spanish
('es', 'footer.description', 'Creando canciones personalizadas significativas para cada ocasión. Una plataforma basada en la fe dedicada a dar vida a sus historias a través de la música.'),
('es', 'footer.faith_values', 'Plataforma basada en la fe • Valores cristianos'),
('es', 'footer.quick_links', 'Enlaces rápidos'),
('es', 'footer.about_us', 'Acerca de nosotros'),
('es', 'footer.song_library', 'Biblioteca de canciones'),
('es', 'footer.pricing', 'Precios'),
('es', 'footer.create_song', 'Crear canción'),
('es', 'footer.testimonies', 'Testimonios'),
('es', 'footer.support', 'Soporte'),
('es', 'footer.faq', 'FAQ'),
('es', 'footer.terms_conditions', 'Términos y condiciones'),
('es', 'footer.contact_us', 'Contáctanos'),
('es', 'footer.support_mission', 'Apoya nuestra misión'),
('es', 'footer.copyright', '© 2025 Zamar. Todos los derechos reservados.'),
('es', 'footer.faith_disclaimer', '🛐 Descargo de responsabilidad basado en la fe: Nos reservamos el derecho de rechazar solicitudes que vayan en contra de nuestros valores cristianos.'),

-- Footer translations - Italian
('it', 'footer.description', 'Creare canzoni personalizzate significative per ogni occasione. Una piattaforma basata sulla fede dedicata a dare vita alle tue storie attraverso la musica.'),
('it', 'footer.faith_values', 'Piattaforma basata sulla fede • Valori cristiani'),
('it', 'footer.quick_links', 'Collegamenti rapidi'),
('it', 'footer.about_us', 'Chi siamo'),
('it', 'footer.song_library', 'Biblioteca musicale'),
('it', 'footer.pricing', 'Prezzi'),
('it', 'footer.create_song', 'Crea canzone'),
('it', 'footer.testimonies', 'Testimonianze'),
('it', 'footer.support', 'Supporto'),
('it', 'footer.faq', 'FAQ'),
('it', 'footer.terms_conditions', 'Termini e condizioni'),
('it', 'footer.contact_us', 'Contattaci'),
('it', 'footer.support_mission', 'Sostieni la nostra missione'),
('it', 'footer.copyright', '© 2025 Zamar. Tutti i diritti riservati.'),
('it', 'footer.faith_disclaimer', '🛐 Disclaimer basato sulla fede: Ci riserviamo il diritto di rifiutare richieste che vanno contro i nostri valori cristiani.'),

-- Footer translations - Portuguese
('pt', 'footer.description', 'Criando canções personalizadas significativas para cada ocasião. Uma plataforma baseada na fé dedicada a dar vida às suas histórias através da música.'),
('pt', 'footer.faith_values', 'Plataforma baseada na fé • Valores cristãos'),
('pt', 'footer.quick_links', 'Links rápidos'),
('pt', 'footer.about_us', 'Sobre nós'),
('pt', 'footer.song_library', 'Biblioteca de músicas'),
('pt', 'footer.pricing', 'Preços'),
('pt', 'footer.create_song', 'Criar canção'),
('pt', 'footer.testimonies', 'Testemunhos'),
('pt', 'footer.support', 'Suporte'),
('pt', 'footer.faq', 'FAQ'),
('pt', 'footer.terms_conditions', 'Termos e condições'),
('pt', 'footer.contact_us', 'Entre em contato'),
('pt', 'footer.support_mission', 'Apoie nossa missão'),
('pt', 'footer.copyright', '© 2025 Zamar. Todos os direitos reservados.'),
('pt', 'footer.faith_disclaimer', '🛐 Aviso baseado na fé: Reservamo-nos o direito de recusar solicitações que vão contra nossos valores cristãos.')

ON CONFLICT (language, key) DO NOTHING;