INSERT INTO app_translations (language, key, value) VALUES 
('en', 'welcome.personalized', 'Personalized for you'),
('en', 'welcome.welcome_back', 'Welcome back'),
('en', 'radio.subtitle', 'Just like your favorite radio station'),
('pt', 'welcome.personalized', 'Personalizado para você'),
('pt', 'welcome.welcome_back', 'Bem-vindo de volta'),
('pt', 'radio.subtitle', 'Como sua estação de rádio favorita'),
('fr', 'welcome.personalized', 'Personnalisé pour vous'),
('fr', 'welcome.welcome_back', 'Bon retour'),
('fr', 'radio.subtitle', 'Comme votre station de radio préférée'),
('es', 'welcome.personalized', 'Personalizado para ti'),
('es', 'welcome.welcome_back', 'Bienvenido de vuelta'),
('es', 'radio.subtitle', 'Como tu estación de radio favorita'),
('de', 'welcome.personalized', 'Für Sie personalisiert'),
('de', 'welcome.welcome_back', 'Willkommen zurück'),
('de', 'radio.subtitle', 'Wie Ihr Lieblings-Radiosender'),
('it', 'welcome.personalized', 'Personalizzato per te'),
('it', 'welcome.welcome_back', 'Bentornato'),
('it', 'radio.subtitle', 'Come la tua stazione radio preferita'),
('ar', 'welcome.personalized', 'مخصص لك'),
('ar', 'welcome.welcome_back', 'مرحباً بعودتك'),
('ar', 'radio.subtitle', 'مثل محطة الراديو المفضلة لديك'),
('zh', 'welcome.personalized', '为您量身定制'),
('zh', 'welcome.welcome_back', '欢迎回来'),
('zh', 'radio.subtitle', '就像您最喜欢的广播电台'),
('hi', 'welcome.personalized', 'आपके लिए व्यक्तिगत'),
('hi', 'welcome.welcome_back', 'वापसी पर स्वागत है'),
('hi', 'radio.subtitle', 'आपके पसंदीदा रेडियो स्टेशन की तरह'),
('sw', 'welcome.personalized', 'Imebadilishwa kwa ajili yako'),
('sw', 'welcome.welcome_back', 'Karibu tena'),
('sw', 'radio.subtitle', 'Kama kituo chako cha redio unachokipenda');