-- Add Hero section translations
INSERT INTO app_translations (language, key, value) VALUES
-- English
('en', 'hero.title_line1', 'Your Story, Your Song'),
('en', 'hero.title_line2', 'Crafted with Purpose'),
('en', 'hero.subtitle', 'Zamar creates custom songs for every occasion – weddings, birthdays, churches, businesses – combining faith and technology to deliver powerful music that speaks.'),
('en', 'hero.stat1', '500+ Happy Clients'),
('en', 'hero.stat2', '24-48hr Delivery'),
('en', 'hero.stat3', 'Faith-Based Platform'),
('en', 'hero.create_song', 'Create Your Song'),
('en', 'hero.see_examples', 'See Examples'),
('en', 'hero.radio', 'Radio'),
('en', 'hero.support_mission', 'Support Our Mission'),
('en', 'hero.empowering_communities', 'Empowering Communities Through Music'),
('en', 'hero.support_description', 'Help us create meaningful music for communities, ministries, and churches worldwide. Every contribution supports hope, healing, and inspiration through custom songs.'),
('en', 'hero.free_songs', 'Free Songs'),
('en', 'hero.global_reach', 'Global Reach'),
('en', 'hero.community', 'Community'),
('en', 'hero.donate_now', 'Donate Now'),
('en', 'hero.earn_referral', 'Earn Referral Bonus'),
('en', 'hero.share_earn', 'Share & Earn Commissions'),
('en', 'hero.referral_description', 'Invite friends to Zamar and earn commission on their purchases. Share the gift of custom music while building your income.'),
('en', 'hero.direct_referrals', 'Direct Referrals'),
('en', 'hero.indirect_referrals', 'Indirect Referrals'),
('en', 'hero.calculate_earnings', 'Calculate Your Earnings'),
('en', 'hero.join_start_earning', 'Join & Start Earning'),
('en', 'hero.guest_referral_description', 'Create an account to get your referral link and start earning commission on every friend who purchases custom songs through your link.'),
('en', 'hero.join_earn', 'Join & Earn'),

-- French
('fr', 'hero.title_line1', 'Votre Histoire, Votre Chanson'),
('fr', 'hero.title_line2', 'Créée avec Intention'),
('fr', 'hero.subtitle', 'Zamar crée des chansons personnalisées pour chaque occasion – mariages, anniversaires, églises, entreprises – alliant foi et technologie pour livrer une musique puissante qui parle.'),
('fr', 'hero.stat1', '500+ Clients Satisfaits'),
('fr', 'hero.stat2', 'Livraison 24-48h'),
('fr', 'hero.stat3', 'Plateforme Basée sur la Foi'),
('fr', 'hero.create_song', 'Créez Votre Chanson'),
('fr', 'hero.see_examples', 'Voir les Exemples'),
('fr', 'hero.radio', 'Radio'),
('fr', 'hero.support_mission', 'Soutenez Notre Mission'),
('fr', 'hero.empowering_communities', 'Autonomiser les Communautés par la Musique'),
('fr', 'hero.support_description', 'Aidez-nous à créer de la musique significative pour les communautés, ministères et églises du monde entier. Chaque contribution soutient l''espoir, la guérison et l''inspiration à travers des chansons personnalisées.'),
('fr', 'hero.free_songs', 'Chansons Gratuites'),
('fr', 'hero.global_reach', 'Portée Mondiale'),
('fr', 'hero.community', 'Communauté'),
('fr', 'hero.donate_now', 'Faire un Don Maintenant'),
('fr', 'hero.earn_referral', 'Gagner un Bonus de Parrainage'),
('fr', 'hero.share_earn', 'Partager et Gagner des Commissions'),
('fr', 'hero.referral_description', 'Invitez des amis sur Zamar et gagnez une commission sur leurs achats. Partagez le cadeau de la musique personnalisée tout en construisant vos revenus.'),
('fr', 'hero.direct_referrals', 'Parrainages Directs'),
('fr', 'hero.indirect_referrals', 'Parrainages Indirects'),
('fr', 'hero.calculate_earnings', 'Calculez Vos Gains'),
('fr', 'hero.join_start_earning', 'Rejoignez et Commencez à Gagner'),
('fr', 'hero.guest_referral_description', 'Créez un compte pour obtenir votre lien de parrainage et commencer à gagner une commission sur chaque ami qui achète des chansons personnalisées via votre lien.'),
('fr', 'hero.join_earn', 'Rejoindre et Gagner'),

-- Spanish
('es', 'hero.title_line1', 'Tu Historia, Tu Canción'),
('es', 'hero.title_line2', 'Creada con Propósito'),
('es', 'hero.subtitle', 'Zamar crea canciones personalizadas para cada ocasión – bodas, cumpleaños, iglesias, empresas – combinando fe y tecnología para entregar música poderosa que habla.'),
('es', 'hero.stat1', '500+ Clientes Felices'),
('es', 'hero.stat2', 'Entrega 24-48h'),
('es', 'hero.stat3', 'Plataforma Basada en la Fe'),
('es', 'hero.create_song', 'Crea Tu Canción'),
('es', 'hero.see_examples', 'Ver Ejemplos'),
('es', 'hero.radio', 'Radio'),
('es', 'hero.support_mission', 'Apoya Nuestra Misión'),
('es', 'hero.empowering_communities', 'Empoderando Comunidades a Través de la Música'),
('es', 'hero.support_description', 'Ayúdanos a crear música significativa para comunidades, ministerios e iglesias en todo el mundo. Cada contribución apoya la esperanza, sanación e inspiración a través de canciones personalizadas.'),
('es', 'hero.free_songs', 'Canciones Gratis'),
('es', 'hero.global_reach', 'Alcance Global'),
('es', 'hero.community', 'Comunidad'),
('es', 'hero.donate_now', 'Donar Ahora'),
('es', 'hero.earn_referral', 'Ganar Bono de Referido'),
('es', 'hero.share_earn', 'Compartir y Ganar Comisiones'),
('es', 'hero.referral_description', 'Invita amigos a Zamar y gana comisión en sus compras. Comparte el regalo de la música personalizada mientras construyes tus ingresos.'),
('es', 'hero.direct_referrals', 'Referidos Directos'),
('es', 'hero.indirect_referrals', 'Referidos Indirectos'),
('es', 'hero.calculate_earnings', 'Calcula Tus Ganancias'),
('es', 'hero.join_start_earning', 'Únete y Empieza a Ganar'),
('es', 'hero.guest_referral_description', 'Crea una cuenta para obtener tu enlace de referido y comenzar a ganar comisión en cada amigo que compre canciones personalizadas a través de tu enlace.'),
('es', 'hero.join_earn', 'Únete y Gana'),

-- German
('de', 'hero.title_line1', 'Deine Geschichte, Dein Song'),
('de', 'hero.title_line2', 'Mit Zweck Erschaffen'),
('de', 'hero.subtitle', 'Zamar erstellt maßgeschneiderte Songs für jeden Anlass – Hochzeiten, Geburtstage, Kirchen, Unternehmen – und verbindet Glauben und Technologie, um kraftvolle Musik zu liefern, die spricht.'),
('de', 'hero.stat1', '500+ Zufriedene Kunden'),
('de', 'hero.stat2', '24-48h Lieferung'),
('de', 'hero.stat3', 'Glaubensbasierte Plattform'),
('de', 'hero.create_song', 'Erstelle Deinen Song'),
('de', 'hero.see_examples', 'Beispiele Ansehen'),
('de', 'hero.radio', 'Radio'),
('de', 'hero.support_mission', 'Unterstütze Unsere Mission'),
('de', 'hero.empowering_communities', 'Gemeinschaften durch Musik Stärken'),
('de', 'hero.support_description', 'Hilf uns, bedeutungsvolle Musik für Gemeinschaften, Dienste und Kirchen weltweit zu schaffen. Jeder Beitrag unterstützt Hoffnung, Heilung und Inspiration durch maßgeschneiderte Songs.'),
('de', 'hero.free_songs', 'Kostenlose Songs'),
('de', 'hero.global_reach', 'Globale Reichweite'),
('de', 'hero.community', 'Gemeinschaft'),
('de', 'hero.donate_now', 'Jetzt Spenden'),
('de', 'hero.earn_referral', 'Empfehlungsbonus Verdienen'),
('de', 'hero.share_earn', 'Teilen und Provisionen Verdienen'),
('de', 'hero.referral_description', 'Lade Freunde zu Zamar ein und verdiene Provision bei ihren Käufen. Teile das Geschenk der maßgeschneiderten Musik und baue dein Einkommen auf.'),
('de', 'hero.direct_referrals', 'Direkte Empfehlungen'),
('de', 'hero.indirect_referrals', 'Indirekte Empfehlungen'),
('de', 'hero.calculate_earnings', 'Berechne Deine Einnahmen'),
('de', 'hero.join_start_earning', 'Beitreten und Verdienen Beginnen'),
('de', 'hero.guest_referral_description', 'Erstelle ein Konto, um deinen Empfehlungslink zu erhalten und bei jedem Freund Provision zu verdienen, der maßgeschneiderte Songs über deinen Link kauft.'),
('de', 'hero.join_earn', 'Beitreten und Verdienen'),

-- Portuguese
('pt', 'hero.title_line1', 'Sua História, Sua Música'),
('pt', 'hero.title_line2', 'Criada com Propósito'),
('pt', 'hero.subtitle', 'Zamar cria músicas personalizadas para cada ocasião – casamentos, aniversários, igrejas, empresas – combinando fé e tecnologia para entregar música poderosa que fala.'),
('pt', 'hero.stat1', '500+ Clientes Felizes'),
('pt', 'hero.stat2', 'Entrega 24-48h'),
('pt', 'hero.stat3', 'Plataforma Baseada na Fé'),
('pt', 'hero.create_song', 'Crie Sua Música'),
('pt', 'hero.see_examples', 'Ver Exemplos'),
('pt', 'hero.radio', 'Rádio'),
('pt', 'hero.support_mission', 'Apoie Nossa Missão'),
('pt', 'hero.empowering_communities', 'Capacitando Comunidades Através da Música'),
('pt', 'hero.support_description', 'Ajude-nos a criar música significativa para comunidades, ministérios e igrejas em todo o mundo. Cada contribuição apoia esperança, cura e inspiração através de músicas personalizadas.'),
('pt', 'hero.free_songs', 'Músicas Grátis'),
('pt', 'hero.global_reach', 'Alcance Global'),
('pt', 'hero.community', 'Comunidade'),
('pt', 'hero.donate_now', 'Doar Agora'),
('pt', 'hero.earn_referral', 'Ganhar Bônus de Indicação'),
('pt', 'hero.share_earn', 'Compartilhar e Ganhar Comissões'),
('pt', 'hero.referral_description', 'Convide amigos para Zamar e ganhe comissão em suas compras. Compartilhe o presente da música personalizada enquanto constrói sua renda.'),
('pt', 'hero.direct_referrals', 'Indicações Diretas'),
('pt', 'hero.indirect_referrals', 'Indicações Indiretas'),
('pt', 'hero.calculate_earnings', 'Calcule Seus Ganhos'),
('pt', 'hero.join_start_earning', 'Junte-se e Comece a Ganhar'),
('pt', 'hero.guest_referral_description', 'Crie uma conta para obter seu link de indicação e começar a ganhar comissão em cada amigo que comprar músicas personalizadas através do seu link.'),
('pt', 'hero.join_earn', 'Junte-se e Ganhe'),

-- Italian
('it', 'hero.title_line1', 'La Tua Storia, La Tua Canzone'),
('it', 'hero.title_line2', 'Creata con Scopo'),
('it', 'hero.subtitle', 'Zamar crea canzoni personalizzate per ogni occasione – matrimoni, compleanni, chiese, aziende – combinando fede e tecnologia per consegnare musica potente che parla.'),
('it', 'hero.stat1', '500+ Clienti Felici'),
('it', 'hero.stat2', 'Consegna 24-48h'),
('it', 'hero.stat3', 'Piattaforma Basata sulla Fede'),
('it', 'hero.create_song', 'Crea La Tua Canzone'),
('it', 'hero.see_examples', 'Vedi Esempi'),
('it', 'hero.radio', 'Radio'),
('it', 'hero.support_mission', 'Sostieni La Nostra Missione'),
('it', 'hero.empowering_communities', 'Potenziare le Comunità Attraverso la Musica'),
('it', 'hero.support_description', 'Aiutaci a creare musica significativa per comunità, ministeri e chiese in tutto il mondo. Ogni contributo sostiene speranza, guarigione e ispirazione attraverso canzoni personalizzate.'),
('it', 'hero.free_songs', 'Canzoni Gratis'),
('it', 'hero.global_reach', 'Portata Globale'),
('it', 'hero.community', 'Comunità'),
('it', 'hero.donate_now', 'Dona Ora'),
('it', 'hero.earn_referral', 'Guadagna Bonus Referral'),
('it', 'hero.share_earn', 'Condividi e Guadagna Commissioni'),
('it', 'hero.referral_description', 'Invita amici su Zamar e guadagna commissioni sui loro acquisti. Condividi il regalo della musica personalizzata mentre costruisci il tuo reddito.'),
('it', 'hero.direct_referrals', 'Referral Diretti'),
('it', 'hero.indirect_referrals', 'Referral Indiretti'),
('it', 'hero.calculate_earnings', 'Calcola I Tuoi Guadagni'),
('it', 'hero.join_start_earning', 'Unisciti e Inizia a Guadagnare'),
('it', 'hero.guest_referral_description', 'Crea un account per ottenere il tuo link di referral e iniziare a guadagnare commissioni su ogni amico che acquista canzoni personalizzate attraverso il tuo link.'),
('it', 'hero.join_earn', 'Unisciti e Guadagna'),

-- Arabic
('ar', 'hero.title_line1', 'قصتك، أغنيتك'),
('ar', 'hero.title_line2', 'مصنوعة بهدف'),
('ar', 'hero.subtitle', 'زمار ينشئ أغاني مخصصة لكل مناسبة – حفلات الزفاف والأعياد والكنائس والأعمال – مع دمج الإيمان والتكنولوجيا لتقديم موسيقى قوية تتحدث.'),
('ar', 'hero.stat1', '500+ عميل سعيد'),
('ar', 'hero.stat2', 'تسليم 24-48 ساعة'),
('ar', 'hero.stat3', 'منصة مبنية على الإيمان'),
('ar', 'hero.create_song', 'أنشئ أغنيتك'),
('ar', 'hero.see_examples', 'شاهد الأمثلة'),
('ar', 'hero.radio', 'راديو'),
('ar', 'hero.support_mission', 'ادعم مهمتنا'),
('ar', 'hero.empowering_communities', 'تمكين المجتمعات من خلال الموسيقى'),
('ar', 'hero.support_description', 'ساعدنا في إنشاء موسيقى ذات معنى للمجتمعات والخدمات والكنائس في جميع أنحاء العالم. كل مساهمة تدعم الأمل والشفاء والإلهام من خلال الأغاني المخصصة.'),
('ar', 'hero.free_songs', 'أغاني مجانية'),
('ar', 'hero.global_reach', 'وصول عالمي'),
('ar', 'hero.community', 'مجتمع'),
('ar', 'hero.donate_now', 'تبرع الآن'),
('ar', 'hero.earn_referral', 'اكسب مكافأة الإحالة'),
('ar', 'hero.share_earn', 'شارك واكسب عمولات'),
('ar', 'hero.referral_description', 'ادع الأصدقاء إلى زمار واكسب عمولة على مشترياتهم. شارك هدية الموسيقى المخصصة أثناء بناء دخلك.'),
('ar', 'hero.direct_referrals', 'إحالات مباشرة'),
('ar', 'hero.indirect_referrals', 'إحالات غير مباشرة'),
('ar', 'hero.calculate_earnings', 'احسب أرباحك'),
('ar', 'hero.join_start_earning', 'انضم وابدأ الكسب'),
('ar', 'hero.guest_referral_description', 'أنشئ حساباً للحصول على رابط الإحالة الخاص بك وابدأ في كسب عمولة من كل صديق يشتري أغاني مخصصة من خلال رابطك.'),
('ar', 'hero.join_earn', 'انضم واكسب'),

-- Chinese
('zh', 'hero.title_line1', '您的故事，您的歌曲'),
('zh', 'hero.title_line2', '用心制作'),
('zh', 'hero.subtitle', 'Zamar为每个场合创作定制歌曲 – 婚礼、生日、教堂、企业 – 结合信仰和技术，提供有力的音乐表达。'),
('zh', 'hero.stat1', '500+ 满意客户'),
('zh', 'hero.stat2', '24-48小时交付'),
('zh', 'hero.stat3', '基于信仰的平台'),
('zh', 'hero.create_song', '创建您的歌曲'),
('zh', 'hero.see_examples', '查看示例'),
('zh', 'hero.radio', '广播'),
('zh', 'hero.support_mission', '支持我们的使命'),
('zh', 'hero.empowering_communities', '通过音乐赋能社区'),
('zh', 'hero.support_description', '帮助我们为全世界的社区、事工和教堂创作有意义的音乐。每一份贡献都通过定制歌曲支持希望、治愈和灵感。'),
('zh', 'hero.free_songs', '免费歌曲'),
('zh', 'hero.global_reach', '全球覆盖'),
('zh', 'hero.community', '社区'),
('zh', 'hero.donate_now', '立即捐赠'),
('zh', 'hero.earn_referral', '赚取推荐奖金'),
('zh', 'hero.share_earn', '分享并赚取佣金'),
('zh', 'hero.referral_description', '邀请朋友使用Zamar并从他们的购买中赚取佣金。在建立收入的同时分享定制音乐的礼物。'),
('zh', 'hero.direct_referrals', '直接推荐'),
('zh', 'hero.indirect_referrals', '间接推荐'),
('zh', 'hero.calculate_earnings', '计算您的收入'),
('zh', 'hero.join_start_earning', '加入并开始赚钱'),
('zh', 'hero.guest_referral_description', '创建账户获取您的推荐链接，并开始从通过您的链接购买定制歌曲的每位朋友那里赚取佣金。'),
('zh', 'hero.join_earn', '加入并赚钱'),

-- Hindi
('hi', 'hero.title_line1', 'आपकी कहानी, आपका गाना'),
('hi', 'hero.title_line2', 'उद्देश्य के साथ तैयार'),
('hi', 'hero.subtitle', 'ज़मार हर अवसर के लिए कस्टम गाने बनाता है – शादियाँ, जन्मदिन, चर्च, व्यवसाय – विश्वास और तकनीक को मिलाकर शक्तिशाली संगीत प्रदान करता है जो बोलता है।'),
('hi', 'hero.stat1', '500+ खुश ग्राहक'),
('hi', 'hero.stat2', '24-48 घंटे डिलीवरी'),
('hi', 'hero.stat3', 'विश्वास-आधारित प्लेटफॉर्म'),
('hi', 'hero.create_song', 'अपना गाना बनाएं'),
('hi', 'hero.see_examples', 'उदाहरण देखें'),
('hi', 'hero.radio', 'रेडियो'),
('hi', 'hero.support_mission', 'हमारे मिशन का समर्थन करें'),
('hi', 'hero.empowering_communities', 'संगीत के माध्यम से समुदायों को सशक्त बनाना'),
('hi', 'hero.support_description', 'दुनियाभर के समुदायों, मंत्रालयों और चर्चों के लिए अर्थपूर्ण संगीत बनाने में हमारी मदद करें। हर योगदान कस्टम गानों के माध्यम से आशा, उपचार और प्रेरणा का समर्थन करता है।'),
('hi', 'hero.free_songs', 'मुफ्त गाने'),
('hi', 'hero.global_reach', 'वैश्विक पहुंच'),
('hi', 'hero.community', 'समुदाय'),
('hi', 'hero.donate_now', 'अभी दान करें'),
('hi', 'hero.earn_referral', 'रेफरल बोनस कमाएं'),
('hi', 'hero.share_earn', 'साझा करें और कमीशन कमाएं'),
('hi', 'hero.referral_description', 'दोस्तों को ज़मार में आमंत्रित करें और उनकी खरीदारी पर कमीशन कमाएं। अपनी आय बढ़ाते हुए कस्टम संगीत का उपहार साझा करें।'),
('hi', 'hero.direct_referrals', 'प्रत्यक्ष रेफरल'),
('hi', 'hero.indirect_referrals', 'अप्रत्यक्ष रेफरल'),
('hi', 'hero.calculate_earnings', 'अपनी कमाई की गणना करें'),
('hi', 'hero.join_start_earning', 'शामिल हों और कमाना शुरू करें'),
('hi', 'hero.guest_referral_description', 'अपना रेफरल लिंक पाने के लिए खाता बनाएं और हर उस दोस्त से कमीशन कमाना शुरू करें जो आपके लिंक के माध्यम से कस्टम गाने खरीदता है।'),
('hi', 'hero.join_earn', 'शामिल हों और कमाएं'),

-- Swahili
('sw', 'hero.title_line1', 'Hadithi Yako, Wimbo Wako'),
('sw', 'hero.title_line2', 'Kuundwa kwa Kusudi'),
('sw', 'hero.subtitle', 'Zamar huunda nyimbo za kibinafsi kwa kila tukio – harusi, miaka ya kuzaliwa, makanisa, biashara – kuunganisha imani na teknolojia kutoa muziki wenye nguvu unaoongea.'),
('sw', 'hero.stat1', '500+ Wateja Wafurahi'),
('sw', 'hero.stat2', 'Utoaji 24-48 Masaa'),
('sw', 'hero.stat3', 'Jukwaa la Kimsingi'),
('sw', 'hero.create_song', 'Unda Wimbo Wako'),
('sw', 'hero.see_examples', 'Ona Mifano'),
('sw', 'hero.radio', 'Redio'),
('sw', 'hero.support_mission', 'Unga Mkono Dhamira Yetu'),
('sw', 'hero.empowering_communities', 'Kuimarisha Jamii Kupitia Muziki'),
('sw', 'hero.support_description', 'Tusaidie kuunda muziki wenye maana kwa jamii, huduma na makanisa duniani kote. Kila mchango unasaidia matumaini, uponyaji na msukumo kupitia nyimbo za kibinafsi.'),
('sw', 'hero.free_songs', 'Nyimbo za Bure'),
('sw', 'hero.global_reach', 'Mfikio wa Kimataifa'),
('sw', 'hero.community', 'Jamii'),
('sw', 'hero.donate_now', 'Toa Mchango Sasa'),
('sw', 'hero.earn_referral', 'Pata Zawadi ya Rufaa'),
('sw', 'hero.share_earn', 'Shiriki na Pata Ushuru'),
('sw', 'hero.referral_description', 'Alika marafiki kwenye Zamar na upate ushuru kutoka manunuzi yao. Shiriki zawadi ya muziki wa kibinafsi huku ukijenga kipato chako.'),
('sw', 'hero.direct_referrals', 'Rufaa za Moja kwa Moja'),
('sw', 'hero.indirect_referrals', 'Rufaa Zisizo za Moja kwa Moja'),
('sw', 'hero.calculate_earnings', 'Hesabu Mapato Yako'),
('sw', 'hero.join_start_earning', 'Jiunge na Anza Kupata'),
('sw', 'hero.guest_referral_description', 'Unda akaunti ili upate kiungo chako cha rufaa na uanze kupata ushuru kutoka kila rafiki anayenunua nyimbo za kibinafsi kupitia kiungo chako.'),
('sw', 'hero.join_earn', 'Jiunge na Pata');