-- Add More page translations
INSERT INTO app_translations (language, key, value) VALUES
-- English
('en', 'more.menu', 'Menu'),
('en', 'more.welcome_back', 'Welcome back, {email}'),
('en', 'more.my_account', 'My Account'),
('en', 'more.dashboard', 'Dashboard'),
('en', 'more.create_playlist', 'Create Playlist'),
('en', 'more.manage_playlists', 'Manage Playlists'),
('en', 'more.pricing', 'Pricing'),
('en', 'more.referral_calculator', 'Referral Calculator'),
('en', 'more.testimonies', 'Testimonies'),
('en', 'more.donate', 'Donate'),
('en', 'more.settings', 'Settings'),
('en', 'more.logout', 'Logout'),
('en', 'more.app_tagline', 'Custom Songs for Every Occasion'),
('en', 'more.version', 'Version 1.0.0'),
('en', 'more.logout_success', 'Logged out'),
('en', 'more.logout_success_description', 'You have been successfully logged out.'),
('en', 'more.logout_error', 'Error'),
('en', 'more.logout_error_description', 'Failed to log out. Please try again.'),

-- French
('fr', 'more.menu', 'Menu'),
('fr', 'more.welcome_back', 'Bon retour, {email}'),
('fr', 'more.my_account', 'Mon Compte'),
('fr', 'more.dashboard', 'Tableau de Bord'),
('fr', 'more.create_playlist', 'Créer une Playlist'),
('fr', 'more.manage_playlists', 'Gérer les Playlists'),
('fr', 'more.pricing', 'Tarifs'),
('fr', 'more.referral_calculator', 'Calculateur de Parrainage'),
('fr', 'more.testimonies', 'Témoignages'),
('fr', 'more.donate', 'Faire un Don'),
('fr', 'more.settings', 'Paramètres'),
('fr', 'more.logout', 'Déconnexion'),
('fr', 'more.app_tagline', 'Chansons Personnalisées pour Chaque Occasion'),
('fr', 'more.version', 'Version 1.0.0'),
('fr', 'more.logout_success', 'Déconnecté'),
('fr', 'more.logout_success_description', 'Vous avez été déconnecté avec succès.'),
('fr', 'more.logout_error', 'Erreur'),
('fr', 'more.logout_error_description', 'Échec de la déconnexion. Veuillez réessayer.'),

-- Spanish
('es', 'more.menu', 'Menú'),
('es', 'more.welcome_back', 'Bienvenido de nuevo, {email}'),
('es', 'more.my_account', 'Mi Cuenta'),
('es', 'more.dashboard', 'Panel de Control'),
('es', 'more.create_playlist', 'Crear Lista de Reproducción'),
('es', 'more.manage_playlists', 'Gestionar Listas de Reproducción'),
('es', 'more.pricing', 'Precios'),
('es', 'more.referral_calculator', 'Calculadora de Referencias'),
('es', 'more.testimonies', 'Testimonios'),
('es', 'more.donate', 'Donar'),
('es', 'more.settings', 'Configuración'),
('es', 'more.logout', 'Cerrar Sesión'),
('es', 'more.app_tagline', 'Canciones Personalizadas para Cada Ocasión'),
('es', 'more.version', 'Versión 1.0.0'),
('es', 'more.logout_success', 'Sesión cerrada'),
('es', 'more.logout_success_description', 'Has cerrado sesión exitosamente.'),
('es', 'more.logout_error', 'Error'),
('es', 'more.logout_error_description', 'Error al cerrar sesión. Por favor, inténtalo de nuevo.'),

-- German
('de', 'more.menu', 'Menü'),
('de', 'more.welcome_back', 'Willkommen zurück, {email}'),
('de', 'more.my_account', 'Mein Konto'),
('de', 'more.dashboard', 'Dashboard'),
('de', 'more.create_playlist', 'Playlist Erstellen'),
('de', 'more.manage_playlists', 'Playlists Verwalten'),
('de', 'more.pricing', 'Preise'),
('de', 'more.referral_calculator', 'Empfehlungsrechner'),
('de', 'more.testimonies', 'Erfahrungsberichte'),
('de', 'more.donate', 'Spenden'),
('de', 'more.settings', 'Einstellungen'),
('de', 'more.logout', 'Abmelden'),
('de', 'more.app_tagline', 'Maßgeschneiderte Songs für Jeden Anlass'),
('de', 'more.version', 'Version 1.0.0'),
('de', 'more.logout_success', 'Abgemeldet'),
('de', 'more.logout_success_description', 'Sie wurden erfolgreich abgemeldet.'),
('de', 'more.logout_error', 'Fehler'),
('de', 'more.logout_error_description', 'Abmeldung fehlgeschlagen. Bitte versuchen Sie es erneut.'),

-- Portuguese
('pt', 'more.menu', 'Menu'),
('pt', 'more.welcome_back', 'Bem-vindo de volta, {email}'),
('pt', 'more.my_account', 'Minha Conta'),
('pt', 'more.dashboard', 'Painel'),
('pt', 'more.create_playlist', 'Criar Playlist'),
('pt', 'more.manage_playlists', 'Gerenciar Playlists'),
('pt', 'more.pricing', 'Preços'),
('pt', 'more.referral_calculator', 'Calculadora de Indicação'),
('pt', 'more.testimonies', 'Testemunhos'),
('pt', 'more.donate', 'Doar'),
('pt', 'more.settings', 'Configurações'),
('pt', 'more.logout', 'Sair'),
('pt', 'more.app_tagline', 'Músicas Personalizadas para Cada Ocasião'),
('pt', 'more.version', 'Versão 1.0.0'),
('pt', 'more.logout_success', 'Desconectado'),
('pt', 'more.logout_success_description', 'Você foi desconectado com sucesso.'),
('pt', 'more.logout_error', 'Erro'),
('pt', 'more.logout_error_description', 'Falha ao desconectar. Tente novamente.'),

-- Italian
('it', 'more.menu', 'Menu'),
('it', 'more.welcome_back', 'Bentornato, {email}'),
('it', 'more.my_account', 'Il Mio Account'),
('it', 'more.dashboard', 'Dashboard'),
('it', 'more.create_playlist', 'Crea Playlist'),
('it', 'more.manage_playlists', 'Gestisci Playlist'),
('it', 'more.pricing', 'Prezzi'),
('it', 'more.referral_calculator', 'Calcolatore Referral'),
('it', 'more.testimonies', 'Testimonianze'),
('it', 'more.donate', 'Dona'),
('it', 'more.settings', 'Impostazioni'),
('it', 'more.logout', 'Disconnetti'),
('it', 'more.app_tagline', 'Canzoni Personalizzate per Ogni Occasione'),
('it', 'more.version', 'Versione 1.0.0'),
('it', 'more.logout_success', 'Disconnesso'),
('it', 'more.logout_success_description', 'Sei stato disconnesso con successo.'),
('it', 'more.logout_error', 'Errore'),
('it', 'more.logout_error_description', 'Errore durante la disconnessione. Riprova.'),

-- Arabic
('ar', 'more.menu', 'القائمة'),
('ar', 'more.welcome_back', 'مرحباً بعودتك، {email}'),
('ar', 'more.my_account', 'حسابي'),
('ar', 'more.dashboard', 'لوحة التحكم'),
('ar', 'more.create_playlist', 'إنشاء قائمة تشغيل'),
('ar', 'more.manage_playlists', 'إدارة قوائم التشغيل'),
('ar', 'more.pricing', 'الأسعار'),
('ar', 'more.referral_calculator', 'حاسبة الإحالة'),
('ar', 'more.testimonies', 'الشهادات'),
('ar', 'more.donate', 'تبرع'),
('ar', 'more.settings', 'الإعدادات'),
('ar', 'more.logout', 'تسجيل الخروج'),
('ar', 'more.app_tagline', 'أغاني مخصصة لكل مناسبة'),
('ar', 'more.version', 'الإصدار 1.0.0'),
('ar', 'more.logout_success', 'تم تسجيل الخروج'),
('ar', 'more.logout_success_description', 'تم تسجيل خروجك بنجاح.'),
('ar', 'more.logout_error', 'خطأ'),
('ar', 'more.logout_error_description', 'فشل في تسجيل الخروج. حاول مرة أخرى.'),

-- Chinese
('zh', 'more.menu', '菜单'),
('zh', 'more.welcome_back', '欢迎回来，{email}'),
('zh', 'more.my_account', '我的账户'),
('zh', 'more.dashboard', '仪表板'),
('zh', 'more.create_playlist', '创建播放列表'),
('zh', 'more.manage_playlists', '管理播放列表'),
('zh', 'more.pricing', '价格'),
('zh', 'more.referral_calculator', '推荐计算器'),
('zh', 'more.testimonies', '见证'),
('zh', 'more.donate', '捐赠'),
('zh', 'more.settings', '设置'),
('zh', 'more.logout', '登出'),
('zh', 'more.app_tagline', '为每个场合定制歌曲'),
('zh', 'more.version', '版本 1.0.0'),
('zh', 'more.logout_success', '已登出'),
('zh', 'more.logout_success_description', '您已成功登出。'),
('zh', 'more.logout_error', '错误'),
('zh', 'more.logout_error_description', '登出失败。请重试。'),

-- Hindi
('hi', 'more.menu', 'मेनू'),
('hi', 'more.welcome_back', 'वापसी पर स्वागत है, {email}'),
('hi', 'more.my_account', 'मेरा खाता'),
('hi', 'more.dashboard', 'डैशबोर्ड'),
('hi', 'more.create_playlist', 'प्लेलिस्ट बनाएं'),
('hi', 'more.manage_playlists', 'प्लेलिस्ट प्रबंधित करें'),
('hi', 'more.pricing', 'मूल्य निर्धारण'),
('hi', 'more.referral_calculator', 'रेफरल कैलकुलेटर'),
('hi', 'more.testimonies', 'गवाही'),
('hi', 'more.donate', 'दान करें'),
('hi', 'more.settings', 'सेटिंग्स'),
('hi', 'more.logout', 'लॉग आउट'),
('hi', 'more.app_tagline', 'हर अवसर के लिए कस्टम गाने'),
('hi', 'more.version', 'संस्करण 1.0.0'),
('hi', 'more.logout_success', 'लॉग आउट हो गया'),
('hi', 'more.logout_success_description', 'आप सफलतापूर्वक लॉग आउट हो गए हैं।'),
('hi', 'more.logout_error', 'त्रुटि'),
('hi', 'more.logout_error_description', 'लॉग आउट करने में विफल। कृपया पुनः प्रयास करें।'),

-- Swahili
('sw', 'more.menu', 'Menyu'),
('sw', 'more.welcome_back', 'Karibu tena, {email}'),
('sw', 'more.my_account', 'Akaunti Yangu'),
('sw', 'more.dashboard', 'Dashibodi'),
('sw', 'more.create_playlist', 'Tengeneza Orodha ya Kucheza'),
('sw', 'more.manage_playlists', 'Simamia Orodha za Kucheza'),
('sw', 'more.pricing', 'Bei'),
('sw', 'more.referral_calculator', 'Kikokotoo cha Rufaa'),
('sw', 'more.testimonies', 'Ushahidi'),
('sw', 'more.donate', 'Changia'),
('sw', 'more.settings', 'Mipangilio'),
('sw', 'more.logout', 'Ondoka'),
('sw', 'more.app_tagline', 'Nyimbo za Kibinafsi kwa Kila Tukio'),
('sw', 'more.version', 'Toleo 1.0.0'),
('sw', 'more.logout_success', 'Umeondoka'),
('sw', 'more.logout_success_description', 'Umeondoka kwa mafanikio.'),
('sw', 'more.logout_error', 'Hitilafu'),
('sw', 'more.logout_error_description', 'Kushindwa kuondoka. Tafadhali jaribu tena.');