INSERT INTO app_translations (language, key, value) VALUES 
-- Playlist management translations
('en', 'playlists.manage_title', 'Manage Playlists'),
('en', 'playlists.manage_subtitle', 'Edit, delete, or view your playlists'),
('en', 'playlists.view_public', 'View Public Playlists'),
('en', 'playlists.new_playlist', 'New Playlist'),
('en', 'playlists.no_playlists', 'You haven''t created any playlists yet.'),
('en', 'playlists.create_first', 'Create Your First Playlist'),
('en', 'playlists.public', 'Public'),
('en', 'playlists.private', 'Private'),
('en', 'playlists.created', 'Created'),
('en', 'playlists.loading', 'Loading playlists...'),
('en', 'playlists.sign_in_required', 'Please sign in to manage your playlists.'),
('en', 'playlists.go_to_login', 'Go to Login'),
('en', 'playlists.error_loading', 'Error loading playlists'),
('en', 'playlists.try_again', 'Please try again later'),
('en', 'playlists.updated', 'Playlist updated'),
('en', 'playlists.updated_success', 'Playlist has been updated successfully.'),

-- Portuguese
('pt', 'playlists.manage_title', 'Gerenciar Listas de Reprodução'),
('pt', 'playlists.manage_subtitle', 'Editar, excluir ou visualizar suas listas de reprodução'),
('pt', 'playlists.view_public', 'Ver Listas Públicas'),
('pt', 'playlists.new_playlist', 'Nova Lista'),
('pt', 'playlists.no_playlists', 'Você ainda não criou nenhuma lista de reprodução.'),
('pt', 'playlists.create_first', 'Criar Sua Primeira Lista'),
('pt', 'playlists.public', 'Pública'),
('pt', 'playlists.private', 'Privada'),
('pt', 'playlists.created', 'Criada'),
('pt', 'playlists.loading', 'Carregando listas...'),
('pt', 'playlists.sign_in_required', 'Por favor, faça login para gerenciar suas listas de reprodução.'),
('pt', 'playlists.go_to_login', 'Ir para Login'),
('pt', 'playlists.error_loading', 'Erro ao carregar listas'),
('pt', 'playlists.try_again', 'Tente novamente mais tarde'),
('pt', 'playlists.updated', 'Lista atualizada'),
('pt', 'playlists.updated_success', 'Lista foi atualizada com sucesso.'),

-- French
('fr', 'playlists.manage_title', 'Gérer les Listes de Lecture'),
('fr', 'playlists.manage_subtitle', 'Modifier, supprimer ou voir vos listes de lecture'),
('fr', 'playlists.view_public', 'Voir les Listes Publiques'),
('fr', 'playlists.new_playlist', 'Nouvelle Liste'),
('fr', 'playlists.no_playlists', 'Vous n''avez pas encore créé de listes de lecture.'),
('fr', 'playlists.create_first', 'Créer Votre Première Liste'),
('fr', 'playlists.public', 'Publique'),
('fr', 'playlists.private', 'Privée'),
('fr', 'playlists.created', 'Créée'),
('fr', 'playlists.loading', 'Chargement des listes...'),
('fr', 'playlists.sign_in_required', 'Veuillez vous connecter pour gérer vos listes de lecture.'),
('fr', 'playlists.go_to_login', 'Aller à la Connexion'),
('fr', 'playlists.error_loading', 'Erreur de chargement des listes'),
('fr', 'playlists.try_again', 'Veuillez réessayer plus tard'),
('fr', 'playlists.updated', 'Liste mise à jour'),
('fr', 'playlists.updated_success', 'La liste a été mise à jour avec succès.'),

-- Spanish
('es', 'playlists.manage_title', 'Gestionar Listas de Reproducción'),
('es', 'playlists.manage_subtitle', 'Editar, eliminar o ver tus listas de reproducción'),
('es', 'playlists.view_public', 'Ver Listas Públicas'),
('es', 'playlists.new_playlist', 'Nueva Lista'),
('es', 'playlists.no_playlists', 'Aún no has creado ninguna lista de reproducción.'),
('es', 'playlists.create_first', 'Crear Tu Primera Lista'),
('es', 'playlists.public', 'Pública'),
('es', 'playlists.private', 'Privada'),
('es', 'playlists.created', 'Creada'),
('es', 'playlists.loading', 'Cargando listas...'),
('es', 'playlists.sign_in_required', 'Por favor, inicia sesión para gestionar tus listas de reproducción.'),
('es', 'playlists.go_to_login', 'Ir al Inicio de Sesión'),
('es', 'playlists.error_loading', 'Error al cargar listas'),
('es', 'playlists.try_again', 'Inténtalo de nuevo más tarde'),
('es', 'playlists.updated', 'Lista actualizada'),
('es', 'playlists.updated_success', 'La lista se ha actualizado correctamente.'),

-- German
('de', 'playlists.manage_title', 'Wiedergabelisten Verwalten'),
('de', 'playlists.manage_subtitle', 'Bearbeiten, löschen oder anzeigen Ihrer Wiedergabelisten'),
('de', 'playlists.view_public', 'Öffentliche Listen Anzeigen'),
('de', 'playlists.new_playlist', 'Neue Wiedergabeliste'),
('de', 'playlists.no_playlists', 'Sie haben noch keine Wiedergabelisten erstellt.'),
('de', 'playlists.create_first', 'Ihre Erste Liste Erstellen'),
('de', 'playlists.public', 'Öffentlich'),
('de', 'playlists.private', 'Privat'),
('de', 'playlists.created', 'Erstellt'),
('de', 'playlists.loading', 'Wiedergabelisten laden...'),
('de', 'playlists.sign_in_required', 'Bitte melden Sie sich an, um Ihre Wiedergabelisten zu verwalten.'),
('de', 'playlists.go_to_login', 'Zur Anmeldung'),
('de', 'playlists.error_loading', 'Fehler beim Laden der Listen'),
('de', 'playlists.try_again', 'Bitte versuchen Sie es später erneut'),
('de', 'playlists.updated', 'Wiedergabeliste aktualisiert'),
('de', 'playlists.updated_success', 'Die Wiedergabeliste wurde erfolgreich aktualisiert.');