-- Add missing translation keys for Pricing page content
INSERT INTO app_translations (key, language, text) VALUES
-- Custom song tiers translations
('pricing.essentials', 'en', 'Essentials'),
('pricing.essentials', 'pt', 'Essenciais'),
('pricing.essentials', 'fr', 'Essentiel'),
('pricing.essentials', 'es', 'Esenciales'),
('pricing.essentials', 'de', 'Grundlagen'),

('pricing.signature', 'en', 'Signature'),
('pricing.signature', 'pt', 'Assinatura'),
('pricing.signature', 'fr', 'Signature'),
('pricing.signature', 'es', 'Firma'),
('pricing.signature', 'de', 'Signatur'),

('pricing.premier', 'en', 'Premier'),
('pricing.premier', 'pt', 'Premier'),
('pricing.premier', 'fr', 'Premier'),
('pricing.premier', 'es', 'Premier'),
('pricing.premier', 'de', 'Premier'),

('pricing.most_popular', 'en', 'Most Popular'),
('pricing.most_popular', 'pt', 'Mais Popular'),
('pricing.most_popular', 'fr', 'Le Plus Populaire'),
('pricing.most_popular', 'es', 'Más Popular'),
('pricing.most_popular', 'de', 'Am Beliebtesten'),

('pricing.limited_availability', 'en', 'Limited Availability'),
('pricing.limited_availability', 'pt', 'Disponibilidade Limitada'),
('pricing.limited_availability', 'fr', 'Disponibilité Limitée'),
('pricing.limited_availability', 'es', 'Disponibilidad Limitada'),
('pricing.limited_availability', 'de', 'Begrenzte Verfügbarkeit'),

-- Custom song descriptions
('pricing.perfect_for_quick', 'en', 'Perfect for quick personal messages'),
('pricing.perfect_for_quick', 'pt', 'Perfeito para mensagens pessoais rápidas'),
('pricing.perfect_for_quick', 'fr', 'Parfait pour les messages personnels rapides'),
('pricing.perfect_for_quick', 'es', 'Perfecto para mensajes personales rápidos'),
('pricing.perfect_for_quick', 'de', 'Perfekt für schnelle persönliche Nachrichten'),

('pricing.most_popular_choice', 'en', 'Most popular choice for special occasions'),
('pricing.most_popular_choice', 'pt', 'Escolha mais popular para ocasiões especiais'),
('pricing.most_popular_choice', 'fr', 'Choix le plus populaire pour les occasions spéciales'),
('pricing.most_popular_choice', 'es', 'Opción más popular para ocasiones especiales'),
('pricing.most_popular_choice', 'de', 'Beliebteste Wahl für besondere Anlässe'),

('pricing.premium_experience', 'en', 'Premium experience with fastest delivery'),
('pricing.premium_experience', 'pt', 'Experiência premium com entrega mais rápida'),
('pricing.premium_experience', 'fr', 'Expérience premium avec la livraison la plus rapide'),
('pricing.premium_experience', 'es', 'Experiencia premium con entrega más rápida'),
('pricing.premium_experience', 'de', 'Premium-Erlebnis mit schnellster Lieferung'),

-- Custom song features
('pricing.feature_1_song', 'en', '1 song'),
('pricing.feature_1_song', 'pt', '1 música'),
('pricing.feature_1_song', 'fr', '1 chanson'),
('pricing.feature_1_song', 'es', '1 canción'),
('pricing.feature_1_song', 'de', '1 Lied'),

('pricing.feature_single_theme', 'en', 'Single theme'),
('pricing.feature_single_theme', 'pt', 'Tema único'),
('pricing.feature_single_theme', 'fr', 'Thème unique'),
('pricing.feature_single_theme', 'es', 'Tema único'),
('pricing.feature_single_theme', 'de', 'Einzelnes Thema'),

('pricing.feature_1_genre', 'en', '1 genre choice'),
('pricing.feature_1_genre', 'pt', '1 escolha de gênero'),
('pricing.feature_1_genre', 'fr', '1 choix de genre'),
('pricing.feature_1_genre', 'es', '1 elección de género'),
('pricing.feature_1_genre', 'de', '1 Genre-Auswahl'),

('pricing.feature_delivery_3_4', 'en', 'Delivery in 3–4 days'),
('pricing.feature_delivery_3_4', 'pt', 'Entrega em 3–4 dias'),
('pricing.feature_delivery_3_4', 'fr', 'Livraison en 3–4 jours'),
('pricing.feature_delivery_3_4', 'es', 'Entrega en 3–4 días'),
('pricing.feature_delivery_3_4', 'de', 'Lieferung in 3–4 Tagen'),

('pricing.feature_mp3_download', 'en', 'MP3 download'),
('pricing.feature_mp3_download', 'pt', 'Download MP3'),
('pricing.feature_mp3_download', 'fr', 'Téléchargement MP3'),
('pricing.feature_mp3_download', 'es', 'Descarga MP3'),
('pricing.feature_mp3_download', 'de', 'MP3-Download'),

('pricing.feature_basic_production', 'en', 'Basic production'),
('pricing.feature_basic_production', 'pt', 'Produção básica'),
('pricing.feature_basic_production', 'fr', 'Production de base'),
('pricing.feature_basic_production', 'es', 'Producción básica'),
('pricing.feature_basic_production', 'de', 'Grundproduktion'),

('pricing.feature_1_song_2_versions', 'en', '1 song in 2 versions'),
('pricing.feature_1_song_2_versions', 'pt', '1 música em 2 versões'),
('pricing.feature_1_song_2_versions', 'fr', '1 chanson en 2 versions'),
('pricing.feature_1_song_2_versions', 'es', '1 canción en 2 versiones'),
('pricing.feature_1_song_2_versions', 'de', '1 Lied in 2 Versionen'),

('pricing.feature_multiple_themes', 'en', 'Multiple themes'),
('pricing.feature_multiple_themes', 'pt', 'Múltiplos temas'),
('pricing.feature_multiple_themes', 'fr', 'Thèmes multiples'),
('pricing.feature_multiple_themes', 'es', 'Múltiples temas'),
('pricing.feature_multiple_themes', 'de', 'Mehrere Themen'),

('pricing.feature_pdf_lyrics', 'en', 'PDF lyrics included'),
('pricing.feature_pdf_lyrics', 'pt', 'Letras em PDF incluídas'),
('pricing.feature_pdf_lyrics', 'fr', 'Paroles PDF incluses'),
('pricing.feature_pdf_lyrics', 'es', 'Letras en PDF incluidas'),
('pricing.feature_pdf_lyrics', 'de', 'PDF-Texte enthalten'),

('pricing.feature_delivery_48_72', 'en', 'Delivery in 48–72 hrs'),
('pricing.feature_delivery_48_72', 'pt', 'Entrega em 48–72 horas'),
('pricing.feature_delivery_48_72', 'fr', 'Livraison en 48–72 heures'),
('pricing.feature_delivery_48_72', 'es', 'Entrega en 48–72 horas'),
('pricing.feature_delivery_48_72', 'de', 'Lieferung in 48–72 Stunden'),

('pricing.feature_high_quality_mp3', 'en', 'High-quality MP3'),
('pricing.feature_high_quality_mp3', 'pt', 'MP3 de alta qualidade'),
('pricing.feature_high_quality_mp3', 'fr', 'MP3 haute qualité'),
('pricing.feature_high_quality_mp3', 'es', 'MP3 de alta calidad'),
('pricing.feature_high_quality_mp3', 'de', 'Hochwertiges MP3'),

('pricing.feature_professional_mixing', 'en', 'Professional mixing'),
('pricing.feature_professional_mixing', 'pt', 'Mixagem profissional'),
('pricing.feature_professional_mixing', 'fr', 'Mixage professionnel'),
('pricing.feature_professional_mixing', 'es', 'Mezcla profesional'),
('pricing.feature_professional_mixing', 'de', 'Professionelles Mixing'),

('pricing.feature_1_minor_revision', 'en', '1 minor revision'),
('pricing.feature_1_minor_revision', 'pt', '1 revisão menor'),
('pricing.feature_1_minor_revision', 'fr', '1 révision mineure'),
('pricing.feature_1_minor_revision', 'es', '1 revisión menor'),
('pricing.feature_1_minor_revision', 'de', '1 kleine Überarbeitung'),

('pricing.feature_2_songs_2_versions', 'en', '2 songs in 2 versions'),
('pricing.feature_2_songs_2_versions', 'pt', '2 músicas em 2 versões'),
('pricing.feature_2_songs_2_versions', 'fr', '2 chansons en 2 versions'),
('pricing.feature_2_songs_2_versions', 'es', '2 canciones en 2 versiones'),
('pricing.feature_2_songs_2_versions', 'de', '2 Lieder in 2 Versionen'),

('pricing.feature_complex_storytelling', 'en', 'Complex storytelling'),
('pricing.feature_complex_storytelling', 'pt', 'Narrativa complexa'),
('pricing.feature_complex_storytelling', 'fr', 'Narration complexe'),
('pricing.feature_complex_storytelling', 'es', 'Narrativa compleja'),
('pricing.feature_complex_storytelling', 'de', 'Komplexes Storytelling'),

('pricing.feature_free_major_revision', 'en', 'Free major revision'),
('pricing.feature_free_major_revision', 'pt', 'Revisão importante gratuita'),
('pricing.feature_free_major_revision', 'fr', 'Révision majeure gratuite'),
('pricing.feature_free_major_revision', 'es', 'Revisión mayor gratuita'),
('pricing.feature_free_major_revision', 'de', 'Kostenlose größere Überarbeitung'),

('pricing.feature_delivery_24_48', 'en', 'Delivery in 24–48 hrs'),
('pricing.feature_delivery_24_48', 'pt', 'Entrega em 24–48 horas'),
('pricing.feature_delivery_24_48', 'fr', 'Livraison en 24–48 heures'),
('pricing.feature_delivery_24_48', 'es', 'Entrega en 24–48 horas'),
('pricing.feature_delivery_24_48', 'de', 'Lieferung in 24–48 Stunden'),

('pricing.feature_studio_quality', 'en', 'Studio-quality production'),
('pricing.feature_studio_quality', 'pt', 'Produção de qualidade de estúdio'),
('pricing.feature_studio_quality', 'fr', 'Production de qualité studio'),
('pricing.feature_studio_quality', 'es', 'Producción de calidad de estudio'),
('pricing.feature_studio_quality', 'de', 'Studioqualitäts-Produktion'),

('pricing.feature_mp3_wav_instrumental', 'en', 'MP3 + WAV + Instrumental versions'),
('pricing.feature_mp3_wav_instrumental', 'pt', 'Versões MP3 + WAV + Instrumental'),
('pricing.feature_mp3_wav_instrumental', 'fr', 'Versions MP3 + WAV + Instrumentale'),
('pricing.feature_mp3_wav_instrumental', 'es', 'Versiones MP3 + WAV + Instrumental'),
('pricing.feature_mp3_wav_instrumental', 'de', 'MP3 + WAV + Instrumentalversionen'),

('pricing.feature_priority_support', 'en', 'Priority support'),
('pricing.feature_priority_support', 'pt', 'Suporte prioritário'),
('pricing.feature_priority_support', 'fr', 'Support prioritaire'),
('pricing.feature_priority_support', 'es', 'Soporte prioritario'),
('pricing.feature_priority_support', 'de', 'Prioritäts-Support'),

-- Order Now button
('pricing.order_now', 'en', 'Order Now'),
('pricing.order_now', 'pt', 'Encomendar Agora'),
('pricing.order_now', 'fr', 'Commander Maintenant'),
('pricing.order_now', 'es', 'Ordenar Ahora'),
('pricing.order_now', 'de', 'Jetzt Bestellen'),

-- Supporter plans
('pricing.supporter_lifetime', 'en', 'Supporter Lifetime'),
('pricing.supporter_lifetime', 'pt', 'Apoiador Vitalício'),
('pricing.supporter_lifetime', 'fr', 'Supporter à Vie'),
('pricing.supporter_lifetime', 'es', 'Seguidor de por Vida'),
('pricing.supporter_lifetime', 'de', 'Unterstützer Lebenslang'),

('pricing.only_first_500', 'en', 'Only first 500 supporters'),
('pricing.only_first_500', 'pt', 'Apenas os primeiros 500 apoiadores'),
('pricing.only_first_500', 'fr', 'Seulement les 500 premiers supporters'),
('pricing.only_first_500', 'es', 'Solo los primeros 500 seguidores'),
('pricing.only_first_500', 'de', 'Nur die ersten 500 Unterstützer'),

('pricing.standard', 'en', 'Standard'),
('pricing.standard', 'pt', 'Padrão'),
('pricing.standard', 'fr', 'Standard'),
('pricing.standard', 'es', 'Estándar'),
('pricing.standard', 'de', 'Standard'),

('pricing.family_church', 'en', 'Family/Church'),
('pricing.family_church', 'pt', 'Família/Igreja'),
('pricing.family_church', 'fr', 'Famille/Église'),
('pricing.family_church', 'es', 'Familia/Iglesia'),
('pricing.family_church', 'de', 'Familie/Kirche'),

('pricing.up_to_5_accounts', 'en', 'up to 5 accounts'),
('pricing.up_to_5_accounts', 'pt', 'até 5 contas'),
('pricing.up_to_5_accounts', 'fr', 'jusqu\'à 5 comptes'),
('pricing.up_to_5_accounts', 'es', 'hasta 5 cuentas'),
('pricing.up_to_5_accounts', 'de', 'bis zu 5 Konten'),

('pricing.save_12', 'en', 'save £12'),
('pricing.save_12', 'pt', 'economize £12'),
('pricing.save_12', 'fr', 'économisez £12'),
('pricing.save_12', 'es', 'ahorra £12'),
('pricing.save_12', 'de', 'spare £12'),

-- Supporter features
('pricing.ad_free_streaming', 'en', 'Ad-free streaming'),
('pricing.ad_free_streaming', 'pt', 'Streaming sem anúncios'),
('pricing.ad_free_streaming', 'fr', 'Streaming sans publicité'),
('pricing.ad_free_streaming', 'es', 'Transmisión sin anuncios'),
('pricing.ad_free_streaming', 'de', 'Werbefreies Streaming'),

('pricing.unlimited_downloads', 'en', 'Unlimited downloads (songs & lyrics)'),
('pricing.unlimited_downloads', 'pt', 'Downloads ilimitados (músicas e letras)'),
('pricing.unlimited_downloads', 'fr', 'Téléchargements illimités (chansons et paroles)'),
('pricing.unlimited_downloads', 'es', 'Descargas ilimitadas (canciones y letras)'),
('pricing.unlimited_downloads', 'de', 'Unbegrenzte Downloads (Lieder & Texte)'),

('pricing.playlist_creation', 'en', 'Playlist creation'),
('pricing.playlist_creation', 'pt', 'Criação de playlist'),
('pricing.playlist_creation', 'fr', 'Création de playlist'),
('pricing.playlist_creation', 'es', 'Creación de listas de reproducción'),
('pricing.playlist_creation', 'de', 'Playlist-Erstellung'),

('pricing.song_suggestion_submissions', 'en', 'Song suggestion submissions'),
('pricing.song_suggestion_submissions', 'pt', 'Submissões de sugestões de música'),
('pricing.song_suggestion_submissions', 'fr', 'Soumissions de suggestions de chansons'),
('pricing.song_suggestion_submissions', 'es', 'Envíos de sugerencias de canciones'),
('pricing.song_suggestion_submissions', 'de', 'Einreichung von Liedvorschlägen'),

('pricing.access_my_library', 'en', 'Access to My Library'),
('pricing.access_my_library', 'pt', 'Acesso à Minha Biblioteca'),
('pricing.access_my_library', 'fr', 'Accès à Ma Bibliothèque'),
('pricing.access_my_library', 'es', 'Acceso a Mi Biblioteca'),
('pricing.access_my_library', 'de', 'Zugang zu Meiner Bibliothek'),

('pricing.all_supporter_perks', 'en', 'All Supporter perks'),
('pricing.all_supporter_perks', 'pt', 'Todos os benefícios de Apoiador'),
('pricing.all_supporter_perks', 'fr', 'Tous les avantages Supporter'),
('pricing.all_supporter_perks', 'es', 'Todos los beneficios de Seguidor'),
('pricing.all_supporter_perks', 'de', 'Alle Unterstützer-Vorteile'),

('pricing.exclusive_playlists', 'en', 'Exclusive playlists'),
('pricing.exclusive_playlists', 'pt', 'Playlists exclusivas'),
('pricing.exclusive_playlists', 'fr', 'Playlists exclusives'),
('pricing.exclusive_playlists', 'es', 'Listas de reproducción exclusivas'),
('pricing.exclusive_playlists', 'de', 'Exklusive Playlists'),

('pricing.early_access_new_releases', 'en', 'Early access to new releases'),
('pricing.early_access_new_releases', 'pt', 'Acesso antecipado a novos lançamentos'),
('pricing.early_access_new_releases', 'fr', 'Accès anticipé aux nouvelles sorties'),
('pricing.early_access_new_releases', 'es', 'Acceso temprano a nuevos lanzamientos'),
('pricing.early_access_new_releases', 'de', 'Frühzugang zu neuen Veröffentlichungen'),

('pricing.behind_scenes_content', 'en', 'Behind-the-scenes content'),
('pricing.behind_scenes_content', 'pt', 'Conteúdo dos bastidores'),
('pricing.behind_scenes_content', 'fr', 'Contenu des coulisses'),
('pricing.behind_scenes_content', 'es', 'Contenido entre bastidores'),
('pricing.behind_scenes_content', 'de', 'Hinter-den-Kulissen-Inhalte'),

('pricing.all_standard_perks', 'en', 'All Standard perks for multiple users'),
('pricing.all_standard_perks', 'pt', 'Todos os benefícios Padrão para múltiplos usuários'),
('pricing.all_standard_perks', 'fr', 'Tous les avantages Standard pour plusieurs utilisateurs'),
('pricing.all_standard_perks', 'es', 'Todos los beneficios Estándar para múltiples usuarios'),
('pricing.all_standard_perks', 'de', 'Alle Standard-Vorteile für mehrere Benutzer'),

-- CTA buttons
('pricing.become_supporter', 'en', 'Become a Supporter'),
('pricing.become_supporter', 'pt', 'Torne-se um Apoiador'),
('pricing.become_supporter', 'fr', 'Devenir un Supporter'),
('pricing.become_supporter', 'es', 'Convertirse en Seguidor'),
('pricing.become_supporter', 'de', 'Unterstützer werden'),

('pricing.subscribe_now', 'en', 'Subscribe Now'),
('pricing.subscribe_now', 'pt', 'Assinar Agora'),
('pricing.subscribe_now', 'fr', 'S\'abonner Maintenant'),
('pricing.subscribe_now', 'es', 'Suscribirse Ahora'),
('pricing.subscribe_now', 'de', 'Jetzt Abonnieren'),

-- Additional services
('pricing.advertiser_packages', 'en', 'Advertiser Packages'),
('pricing.advertiser_packages', 'pt', 'Pacotes de Anunciante'),
('pricing.advertiser_packages', 'fr', 'Packages Publicitaires'),
('pricing.advertiser_packages', 'es', 'Paquetes de Anunciante'),
('pricing.advertiser_packages', 'de', 'Werbepakete'),

('pricing.pay_per_download', 'en', 'Pay-Per-Download'),
('pricing.pay_per_download', 'pt', 'Pagar Por Download'),
('pricing.pay_per_download', 'fr', 'Paiement Par Téléchargement'),
('pricing.pay_per_download', 'es', 'Pago Por Descarga'),
('pricing.pay_per_download', 'de', 'Pay-Per-Download'),

('pricing.banner_ads', 'en', 'Banner Ads'),
('pricing.banner_ads', 'pt', 'Anúncios Banner'),
('pricing.banner_ads', 'fr', 'Bannières Publicitaires'),
('pricing.banner_ads', 'es', 'Anuncios Banner'),
('pricing.banner_ads', 'de', 'Banner-Werbung'),

('pricing.audio_ads', 'en', 'Audio Ads'),
('pricing.audio_ads', 'pt', 'Anúncios de Áudio'),
('pricing.audio_ads', 'fr', 'Publicités Audio'),
('pricing.audio_ads', 'es', 'Anuncios de Audio'),
('pricing.audio_ads', 'de', 'Audio-Werbung'),

('pricing.combo_banner_audio', 'en', 'Combo (Banner + Audio)'),
('pricing.combo_banner_audio', 'pt', 'Combo (Banner + Áudio)'),
('pricing.combo_banner_audio', 'fr', 'Combo (Bannière + Audio)'),
('pricing.combo_banner_audio', 'es', 'Combo (Banner + Audio)'),
('pricing.combo_banner_audio', 'de', 'Kombo (Banner + Audio)'),

('pricing.single_song', 'en', 'Single Song'),
('pricing.single_song', 'pt', 'Música Única'),
('pricing.single_song', 'fr', 'Chanson Unique'),
('pricing.single_song', 'es', 'Canción Individual'),
('pricing.single_song', 'de', 'Einzellied'),

('pricing.album', 'en', 'Album'),
('pricing.album', 'pt', 'Álbum'),
('pricing.album', 'fr', 'Album'),
('pricing.album', 'es', 'Álbum'),
('pricing.album', 'de', 'Album'),

('pricing.bundle_10_songs', 'en', 'Bundle: 10 songs'),
('pricing.bundle_10_songs', 'pt', 'Pacote: 10 músicas'),
('pricing.bundle_10_songs', 'fr', 'Bundle: 10 chansons'),
('pricing.bundle_10_songs', 'es', 'Paquete: 10 canciones'),
('pricing.bundle_10_songs', 'de', 'Paket: 10 Lieder'),

('pricing.advertise_with_us', 'en', 'Advertise with Us'),
('pricing.advertise_with_us', 'pt', 'Anuncie Conosco'),
('pricing.advertise_with_us', 'fr', 'Annoncez avec Nous'),
('pricing.advertise_with_us', 'es', 'Anúnciese con Nosotros'),
('pricing.advertise_with_us', 'de', 'Werben Sie mit uns'),

('pricing.buy_now', 'en', 'Buy Now'),
('pricing.buy_now', 'pt', 'Comprar Agora'),
('pricing.buy_now', 'fr', 'Acheter Maintenant'),
('pricing.buy_now', 'es', 'Comprar Ahora'),
('pricing.buy_now', 'de', 'Jetzt Kaufen'),

-- Additional pricing keys
('pricing.or', 'en', 'or'),
('pricing.or', 'pt', 'ou'),
('pricing.or', 'fr', 'ou'),
('pricing.or', 'es', 'o'),
('pricing.or', 'de', 'oder');