// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtnebvhrjnpygkftjreo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0bmVidmhyam5weWdrZnRqcmVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTgyMTEsImV4cCI6MjA2OTg5NDIxMX0.wvJKP1_ElkexhVY84VPYT_FjTEx_f-kYYJIW_y5XReg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});